### ISSUE TITLE
How can I upload attachments (e.g. images) using the media WP-API endpoint?

### ISSUE THREAD

**Issue by vtripolitakis** [WP-API/node-wpapi#116]
Here's my code using request:

```javascript
var request = require('request');
	var fs = require('fs');

	var formData = {
  		file: fs.createReadStream('path_and_filename')
	};

	request.post({url:media_endpoint_url, formData: formData}, 
		function optionalCallback(err, httpResponse, body) {	
		  if (err) {
		    return console.error('upload failed:', err);
		  }
		  console.log('Upload successful!  Server responded with:', body);
		})
	.auth('username','password',true);
```

**Comment by tommedema** [comment]
is this implemented?

**Comment by smedegaard** [comment]
@kadamwhite, you marked this as ready but he issue is still open. What is the status? WIll we be able to use `wp.media().post()` for uploading media ?

**Comment by kadamwhite** [comment]
That's still the plan -- but "ready" in this case is a side-effect of our waffle.io setup, and just means this ticket is ready to be started, not that it's finished. Apologies for the ambiguity

**Comment by kadamwhite** [comment]
This is now [supported](https://github.com/WP-API/node-wpapi#uploading-media) by v0.9!
