### ISSUE TITLE
Proposal: posts and pages API filtering

### ISSUE THREAD

**Issue by leobalter** [WP-API/node-wpapi#121]
Looking at the docs on examples like: 

``` js
wp.posts().id( n ).revisions()
wp.posts().type( type_name )
```

How about fetching only a small subset of posts and pages directly on `posts` or `pages` methods as:

``` js
wp.posts('id', n).revisions()
wp.posts('type', type_name);
```

On a future this can be also improved to pass a object with more includes like:

``` js
wp.posts({
  id: n,
  type: type_name
});
```

This proposal should regard it might conflict with a way to set what you want from the posts, let's say you only want to fetch the comments:

``` js
wp.posts({
  type: type_name,
  fetch: [ 'comments' ]
});
```

These ideas are inspired on my previous experience with Ember, and they're just suggestions which I'm sure you'll take the best decision if it's a good improvement or not for this api.

**Comment by kadamwhite** [comment]
@leobalter Thank you for the suggestion! I've been thinking about ways to implement this and the object form, such as
```js
```

**Comment by leobalter** [comment]
the way you presented is great because it works better on the single responsibility pattern and it's less magical than jQuery-like methods we are used to (e.g.: `$.ajax`).

Your approach seems as a great approach as you're working on a web application library.

**Comment by kadamwhite** [comment]
I do not see a way forward to implement this API without impacting the ability to provide configuration options to a WPRequest instance, as well -- these signatures would both have to work,

```js
site.posts({
  nonce: 'authentication-nonce'
});
```
and
```js
site.posts({
  id: 1178
});
```
I don't see a good way to differentiate between the two, especially given that a user-created endpoint could define its own `nonce` query parameter (_e.g._) so even a key whitelist would not be a guarantor of difference. This is a good idea for a simpler API, but between January & now we haven't found a convenient way to add it and at this point I think we should close this out in favor of focusing on the existing interface.
