### ISSUE TITLE
Auth issue.

### ISSUE THREAD

**Issue by andreipot** [WP-API/node-wpapi#151]
@kadamwhite  Adam, have questions.

1.How can I authenticate a user using his wordpress account email/password using this library?

2.And once logged in, how can we sustain his information in cookie or whatever and use it for furher access to APIs?

thanks.

**Comment by andreipot** [comment]
@kadamwhite  here's what I have set up.
backend( wordpress site) : installed wp api v2, member house plugin ,basic HTTP authentication plugin.

frontend: node app.

function authenticateUserWP(email, password) {
  return new Promise(function(resolve, reject){
    var URL = Config.wpapi.endPoint;
   var wp = new WP({
        endpoint: URL ,
        username: email,
        password: password,
        auth: true
    });
   wp.users().then(function(data){
     console.log('wp authenticate--------------');
     console.log(data);
      resolve(data);
   }, function(err){
      reject(err);
   });
  });
}

However above code shows admin account not the one I entered using email/ password. Any idea why it's not working @kadamwhite ?

thanks.

**Comment by kadamwhite** [comment]
@andreipot The way that authentication works with this client, the request that is being returned will match the authentication you pass in with the request. So if you want to enable your users to log in to your application, then provide them with their own WordPress content, you have two options:

1. Make a new `WP` instance for each user, and instantiate it based on their own login credentials, which they would need to provide to you as part of their authentication with your node app; or
2. re-authenticate each request from a single shared `WP` instance with each user's credentials, such as the below pseudo-code example

```js

var wp = new WP({
  endpoint: Config.wpapi.endPoint
});

function authenticateUserWP( username, password ) {
  // Start a /users request,
  return wp.users()
    // then authorize it with the provided username (not email) and password
    .auth({
      username: username,
      password: password
    });
}

authenticateUserWP( 'someuser', 'some password' )
	.me()
	.then(function( userInfo ) {
		console.log( userInfo );
	});
```
The major differences from the approach you've been trying are that you `.auth` the request only once you know the user's credentials, not before; and that you use the user's WP username, not email. In my own tests I haven't been able to get the Basic Auth plugin to work with an email address, though I don't know for sure whether or not that is meant to be supported.

**Comment by kadamwhite** [comment]
I forgot to respond to your second Q,

> And once logged in, how can we sustain his information in cookie or whatever and use it for furher access to APIs?

Login credentials would need to be stored with the user's information in your node application, either in session or in a database; they would be re-used every time that user made an authenticated request. The WP part of the equation has no sense of persistence, so you can't "log them in" through the API: you instead have to authenticate each request you send, and maintain that login state within your own node application.

May I ask you to also review #140? I'd like to continue that conversation.

**Comment by kadamwhite** [comment]
@andreipot I wanted to check in with you on this, I am closing the issue due to lack of response but please re-open it if you have further questions!

**Comment by andreipot** [comment]
@kadamwhite  thanks. I resolved this myself longtime ago. But I really appreciate your help.

**Comment by kadamwhite** [comment]
@andreipot Great to hear it! If you have any suggestions of how we could improve the documentation around this, please don't hesitate to suggest them. All the best!
