### ISSUE TITLE
Creating a post with featured image, categories, and tags

### ISSUE THREAD

**Issue by tommedema** [WP-API/node-wpapi#153]
I'm trying to create a post with a featured image, categories, and tags. I think this would be a good addition to the readme.

Could you give me some hints on how to do this? I could submit a pull request for the readme.

**Comment by vtripolitakis** [comment]
Hello, I 've got some code here. Currently, it's quick and dirty. For the image upload I use the request module. Have a look:
https://github.com/vtripolitakis/nscrape/blob/master/wordpressUtil.js

**Comment by kadamwhite** [comment]
Bumping an old docs issue, @tommedema @vtripolitakis v0.9.1 (live now on NPM) contains [media upload support](https://github.com/wp-api/node-wpapi#uploading-media) -- if you use it and encounter any issues please let us know, I'm be working on a [guide](http://wp-api.org/node-wpapi/) for this functionality but would encourage you to write your own too, if you want to!
