### ISSUE TITLE
Posting into custom post type

### ISSUE THREAD

**Issue by aedensixty** [WP-API/node-wpapi#163]
Posting a new post into a custom post type?

Is this possible or am I just doing it wrong.

I tried 'wp.posts().type('travels').post({' and wp.posts().post({type: "customtype"'.

I also tried using the custom post type endpoint when initialising 'http://site.local/wp-json/wp/v2/customtype'.

**Comment by aedensixty** [comment]
I think I just read in the docs that custom post type has been temporarily removed. Would it be possible to know long will this functionality take to be reinstated?

**Comment by kadamwhite** [comment]
@aedensixty Getting CPT's back in is a priority of mine for the coming two weeks, actually; so if you don't see movement in that time, feel free to bug me about it :)

**Comment by aedensixty** [comment]
Sounds good and you can be sure I will, haha.

**Comment by chrishutchinson** [comment]
Hey @kadamwhite - any movement on CPT support?

**Comment by aedensixty** [comment]
Any news on this?

**Comment by jupitercow** [comment]
I am going to keep an eye on this library, but I switched to using using straight [SuperAgent](https://github.com/visionmedia/superagent), and it has been pretty great. Full API, and only have to manage one documentation (once you get the hang of SuperAgent). 

There a lot of great work going on here, and the next step sounds like it going to be awesome, so definitely interested in checking that out. Just don't have time this week to keep dealing with it, and I HAVE to have custom post types now. 

For those asking, check out #145

**Comment by kadamwhite** [comment]
@jupitercow totally understandable, development lagged for a while. When you already have the URL for the resource you want super agent is a good solution, this is after all little more than a query builder :) If you have time I would welcome your input on #176, which will likely merge and be released in the next 48 hours barring substantive API questions or criticisms

**Comment by kadamwhite** [comment]
Closing as provisionally solved by the custom post type support introduced prior to the current v0.8; please open a new issue if you have future difficulties.
