### ISSUE TITLE
Post with ACF value

### ISSUE THREAD

**Issue by BenHen75** [WP-API/node-wpapi#167]
Hi,

Thanks for this plugin API.

I am trying to add or update a post with an ACF value (https://www.advancedcustomfields.com/), like:

```
wp.posts().id( 180 ).post({

    acf: {theme: "test"}
    
}).then(function( response ) {

    console.log( response.id );

})
```

I activate acf-to-rest-api (https://github.com/airesvsg/acf-to-rest-api) and WP API 2.0 on my wordpress site.

It doest work, maybe because to update acf value it's another endoint: 
`endpoint: 'http://website.com/wp-json/acf'` but authorization fail if I change it.

**Comment by kadamwhite** [comment]
@BenHen75 Thanks for opening this, we've got support in the works ( #176 ) for custom routes like ACF and other recent changes ( #145 ) set us up to automatically create a `wp.namespace( 'acf' )...` handler method if your site is detected to be using that plugin, but neither piece of functionality is live yet. Please take a look at #176 and let me know if you think it would suit your needs, and keep an eye out for autodiscovery support hopefully some time in the next week.

**Comment by kadamwhite** [comment]
I'm provisionally closing this out as resolved by the registerRoute method added in a previous release, but @BenHen75 if you find the custom route support doesn't solve your problem please re-open the issue so we can get you sorted.
