### ISSUE TITLE
Allow insecure/self-signed certificate connection

### ISSUE THREAD

**Issue by bt** [WP-API/node-wpapi#184]
I'm trying to use this with a WordPress installation that I have, but it currently has a self-signed certificate, so I end up with a `Error: self signed certificate`.

Is there a way I can force it to connect?

**Comment by bt** [comment]
Found a hacky fix, which is to add the following line before `require('wordpress-rest-api');`

```
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
```

Still, would be good to get this documented in the README.

**Comment by kadamwhite** [comment]
Thanks for the report, @bt! If you could submit a pull request documenting this nuance that would be great, otherwise I'll try to tackle this soon.

**Comment by bt** [comment]
Easy done! :)

**Comment by bt** [comment]
Haha, I just realised I noobishly made the PR against my own local repository instead of yours. Here it is again, #186

**Comment by Jamiewarb** [comment]
Thanks, this was super helpful
