### ISSUE TITLE
how can upload media?

### ISSUE THREAD

**Issue by z-avanes** [WP-API/node-wpapi#185]
is there any way to upload media?

**Comment by kadamwhite** [comment]
There should be, this needs to be tested and documented. Thanks for the reminder, this has been noted as a deficiency in #116 as well—Now that auto-discovery is sorted I'm moving this up in priority, so hopefully we'll have an answer for you this week!

**Comment by z-avanes** [comment]
thank you so much. i will be waiting for this new feature
i am working with uploadFile feature in xml-rpc client https://github.com/scottgonzalez/node-wordpress and handel my demand but i have one problem with this method ( when upload media can not define alt and name for it ) if you can wp api allow please add this feature to wordpress-rest-api
thanks

**Comment by kadamwhite** [comment]
@z-avanes I forgot to come back to this issue, apologies -- we've got media support as of the latest release, you can see the [documentation](http://wp-api.org/node-wpapi/using-the-client/#uploading-media) and a related [user guide](http://wp-api.org/node-wpapi/guides/2016/08/15/create-a-post-with-featured-media.html) on our docs site. I'm going to close this out as provisionally resolved but if the new methods don't work for you please open a new one so we can improve our documentation. Thank you!

**Comment by z-avanes** [comment]
if find problem report in new issue
thank you @kadamwhite
