### ISSUE TITLE
Usage without WP-API Plugin

### ISSUE THREAD

**Issue by joneslloyd** [WP-API/node-wpapi#191]
Hi there,

I think I already know the answer to this, but want to ask to be absolutely sure:

Is there any way of using this without having the WP-API plugin installed? The reason being, I want to release a stand-alone WordPress plugin (coded in React) using node-wpapi, and I can't tell users to download another plugin (WP-API) first before mine works.

Just want to be doubly sure on this before I (for now) abandon hope :)

Thanks!

**Comment by kadamwhite** [comment]
Are you going to be using the native routes, such as /posts and /comments; or are you going to be defining your own routes? If the latter, you should not need the API plugin installed, as the infrastructure for creating routes I believe to be part of WordPress core itself. 

If you wish to use the routes the WP-API plugin provides for base WordPress content types, then yes, you will need your users to have installed the WP-API plugin, or to somehow include it within your own code

**Comment by joneslloyd** [comment]
Thanks for getting back to me!

A custom endpoint solved it - I can still use `node-wpapi` :) Cheers
