### ISSUE TITLE
Create post

### ISSUE THREAD

**Issue by mrkrumhausen** [WP-API/node-wpapi#192]
I can't seem to add a post. I'm getting this error when I follow the example in the readme: 

> TypeError: wp.posts(...).create is not a function

Code:
```
wp.posts().create({
    // "title" and "content" are the only required properties
    title: 'Your Post Title',
    content: 'Your post content',
    // Post will be created as a draft by default if a specific "status"
    // is not specified
    status: 'publish'
}).then(function( response ) {
    // "response" will hold all properties of your newly-created post,
    // including the unique `id` the post was assigned on creation
    console.log( response.id );
})
```

I also tried to change it to wp.posts().post which gives me this error:

> Unhandled rejection Error: Unauthorized

**Comment by kadamwhite** [comment]
Can you share the version of the module that you are using, as well as your current version of node ? Thanks!

**Comment by mrkrumhausen** [comment]
Sure!
wpapi 0.8.0,
Node v5.1.0

**Comment by kadamwhite** [comment]
@mrkrumhausen I'm not sure what to make of this, the [integration test](https://github.com/WP-API/node-wpapi/blob/master/tests/integration/posts.js#L305) for this functionality is working as expected. What approach are you taking to generate the `wp` object; `WP.site()`, `new WP`, `WP.bootstrap`?

**Comment by mrkrumhausen** [comment]
```
function createPost(){
	wp.posts().create({
	    title: 'Your Post Title',
	    content: 'Your post content',
	}).then(function( response ) {
	    console.log( response.id );
	});
}
createPost();
```

Error message in terminal:

```
Warning: method .parent() is already defined!
Cannot overwrite .pages().parent() method
Unhandled rejection Error: Unauthorized
    at Request.callback (/.../node_modules/superagent/lib/node/index.js:698:17)
    at Stream.<anonymous> (/.../node_modules/superagent/lib/node/index.js:922:12)
    at emitNone (events.js:91:20)
    at Stream.emit (events.js:185:7)
    at Unzip.<anonymous> (/.../node_modules/superagent/lib/node/utils.js:108:12)
    at emitNone (events.js:91:20)
    at Unzip.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by kadamwhite** [comment]
OK, the issue looks like you're not authenticated with the host. You'll need to use the basic auth plugin, and provide a `username` and `password` when creating the WP object, as per the Authentication instructions in the README. For example:

```js
var WP = require('wpapi');
var wp = new WP({
  endpoint: 'http://your.website.com/wp-json',
  username: 'The username of a user authorized to create posts',
  password: 'That users password'
});

wp.posts().create({ etc: 'etera' });
```

Let me know if that works! OAuth support is a known shortcoming of this library, we're working on it but it's taking a while so you can also check out e.g. https://github.com/joehoyle/wordpress-rest-api-oauth-1

**Comment by mrkrumhausen** [comment]
Ok thanks. I'll check that out. I am authenticating with a wp user. I created a new wp test-user and gave it editor rights.

```
var WP = require( 'wpapi' );
// connect to WP site
var wp = new WP({
    endpoint: 'http://somesite.com/wp-json',
    username: 'testuser',
    password: 'password',
});
```

**Comment by kadamwhite** [comment]
Just to try to cover all the bases, do you have the [Basic Auth plugin](https://github.com/wp-api/basic-auth) installed and activated?

**Comment by mrkrumhausen** [comment]
Yes. That helped. Thanks! Didn't know I needed that extra plugin. It says it's for development?!

Maybe add that to the documentation?

**Comment by mrkrumhausen** [comment]
Another question :)
How do I add categories, tags and custom fields when creating posts?

**Comment by kadamwhite** [comment]
@mrkrumhausen Can I ask you to ask that other question in a new issue? :) I'm going to close this one.

As to the documentation note, we currently mention the basic auth plugin both in the [authentication section](https://github.com/WP-API/node-wpapi/#authentication) of this plugin and the [authentication guide](http://v2.wp-api.org/guide/authentication/#application-passwords-or-basic-authentication) on the docs site, but I'm open to adding more references if you have suggestions for other callouts.

**Comment by mrkrumhausen** [comment]
Maybe change the structure of the readme so there is a section on methods/function, authenticate would be a standalone title. You could bold the line where you call out that another FB plugin is needed.

**Comment by kadamwhite** [comment]
Good suggestion, thank you! We're close to v0.9 (with media support) and could sneak a docs reorg in there.
