### ISSUE TITLE
How to add categories, tags and custom fields when creating posts?

### ISSUE THREAD

**Issue by mrkrumhausen** [WP-API/node-wpapi#195]
This doesn't seem to work for me
```
function createPost(){
	wp.posts().create({
	    title: data.title,
	    content: data.subtitle,
	    tag: [ 'vegan', 'dinner' ],
	    category: [ 'berlin', 'copenhagen' ],

	}).then(function( response ) {
	    // "response" will hold all properties of your newly-created post,
	    // including the unique `id` the post was assigned on creation
	    console.log("post created with id: " + response.id );
	});
}
```

**Comment by kadamwhite** [comment]
I'm AFK for the night, but at a first glance: try replacing the "category" property with a `.categories` array, containing the numeric IDs of the categories to add, rather than the slugs. (Possibly the same slug -> ID change will be needed with tags, as well; all WP internal relationships are governed by ID, because slugs are mutable public-facing data). See more about the properties accepted by the posts endpoint here: http://v2.wp-api.org/reference/posts/#schema-categories

**Comment by kadamwhite** [comment]
If that doesn't work, please paste the error you get back and we'll continue the conversation in the morning! Thanks much.

**Comment by mrkrumhausen** [comment]
Cool. Thx

I added .tags(25) but it didn't work. It gave me this error:

`wp.posts(...).id(...).post(...).tags is not a function`

I'm not sure how to reference a specific post and then add a tag to it.

```
function createPost(){
	wp.posts()
		.create({
		    title: "title",
		    content: "content",
		    })
		.tags(25)
		.then(function( response ) {
	    console.log("post created with id: " + response.id );
	});
}
```

**Comment by kadamwhite** [comment]
The chaining methods `.category` and `.tag` are only for filtering collections; if you're creating a post, you'll want to include the `.tags` or `.categories` arrays in the post data object, as you had it in the initial post up above. So, if we imagine 'vegan' is tag ID #1, 'dinner' is ID #2, category 'berlin' is ID #3, and 'copenhagen' is #4:

```js
wp.posts().create({
    title: data.title,
    content: data.subtitle,
    tags: [ 1, 2 ],
    categories: [ 3, 4 ]
}).then(function( response ) {
    console.log( 'Post created with ID ' + response.id );
    console.log( 'Post categories: ' + response.categories.join() );
    console.log( 'Post tags: ' + response.tags.join() );
});
```
Hope that helps!

**Comment by mrkrumhausen** [comment]
It works, but I'm curious - is there no way to add tags or categories using slugs? Not even a hack just for development purposes?

**Comment by kadamwhite** [comment]
@mrkrumhausen I do not believe so, but that'd be a good question to ask over on the [main WP REST API repository](https://github.com/wp-api/wp-api).

I'm going to close this out, thanks for raising the issue and let me know if you run into any further trouble!
