### ISSUE TITLE
"method .parent() is already defined" when creating a new client

### ISSUE THREAD

**Issue by elyobo** [WP-API/node-wpapi#199]
Creating a client with an endpoint always complains about trying to overwrite the `.pages.parent()` method.  Everything still works, but the message is annoying (and noisy in the logs).

```
> const WP = require('wpapi');
undefined
> const client = new WP({ endpoint: 'http://double-bay.rwoffice1.com/wp-json/' });
Warning: method .parent() is already defined!
Cannot overwrite .pages().parent() method
```

**Comment by kadamwhite** [comment]
Thanks for the issue, @elyobo -- that's a great point, I've added a PR to suppress the warning. The situations where it will provide useful information are greatly outnumbered by the situations where it just provides too much noise.

**Comment by kadamwhite** [comment]
Resolved, and the beta tag has been updated with the latest master

**Comment by elyobo** [comment]
Great, thanks for such a quick resolution to such a minor issue :)
