### ISSUE TITLE
Update taxonomy term query methods to utilize latest API changes

### ISSUE THREAD

**Issue by akmur** [WP-API/node-wpapi#204]
Hello,
great job on this package. I am trying to find a way to filter out a category from my posts collection, is it feasible? I tried using something like -1 (where 1 is the id of the category), similarly to what is done in WordPress custom loops, but it won't work.

Any idea is appreciated, thanks!

**Comment by kadamwhite** [comment]
Hey @akmur, thanks for the question. I just returned from holiday and I'm getting things back in order, I'll dig in to what would be necessary to accomplish what you want in the next couple days; apologies for the delay.

**Comment by akmur** [comment]
Actually I just retried and it would seem like it does work, I don't know why it was not working before, probably some mistake of mine.

I was able to get this to work

`wp.posts().category(-67).then(function( data ) {
          res.render('posts', { posts: data });
});`

So I'd say it's already implemented, maybe you could just doublecheck it :)

Thanks a lot

**Comment by kadamwhite** [comment]
@akmur after digging into this, there's a lot of inconsistency over how the `cat` filter parameter is handled by the API; and internally, we weren't always accurate about how we tracked method inputs. if your test somehow ended up trying to pass `category()` a string, like `'-67'` instead of `-67`, it probably would not have worked. I've got a branch that takes care of that, and intend to raise the overall category inconsistency question with the API leads.

**Comment by kadamwhite** [comment]
Since it sounds like you're sorted, I'm taking over this issue to account for updating the taxonomy filtering logic to reflect the latest and greatest in the REST API betas

**Comment by akmur** [comment]
Yes, I think i'm kind of sorted :) Many thanks!

**Comment by kadamwhite** [comment]
@akmur Just a heads-up if you haven't seen it already that this will likely NOT work in 4.7, due to changes to how categories are included and excluded (`filter` has been removed).

**Comment by kadamwhite** [comment]
This should be handled as best we can as of v0.12, which includes `.categories()` and `.tags()` methods to provide OR queries for taxonomies, and `.excludeCategories()` and `.excludeTags()` methods to provide NOT IN queries. AND handling is [not currently supported by the API](https://github.com/WP-API/WP-API/issues/2768).
