### ISSUE TITLE
Right way to call wp.users().me()

### ISSUE THREAD

**Issue by wblaircox** [WP-API/node-wpapi#206]
After nearly two weeks of trying to get WP-API working for my simple project/use, I've landed here thanks to @kadamwhite. I'm running a simple JS app within a Wordpress page. I want to save data specific to the logged-in user to the database. Using WP-API is ideal for this in my case. I'm nearly there, finally! Except for that bloody infuriating authentication again. I'm accessing draft/private posts.

So, how exactly do I;

```
function getPosts() {
    //wp.users().auth("USER","PASS").me();
    wp.posts().users().me().context('edit').param('status', 'draft').then(function (posts) {
        console.log(posts);
    });
};
```

But make sure the current WP User is authenticated? wp.users().me() looks about right, but what is the correct method?

Thanks!

**Comment by wblaircox** [comment]
As with all the other methods of using WP-API, I can get it to work just fine for published posts. But authentication escapes me. Does anyone have any tips or suggestions on what I'm doing incorrectly?

**Comment by kadamwhite** [comment]
@wblaircox we've got a guide in progress that'll help you out a lot, I'm slammed with day job rn but will try to get it online within the next day.

**Comment by kadamwhite** [comment]
@wblaircox let us know if this does the trick: http://wp-api.org/node-wpapi/guides/2016/08/12/authenticating-with-cookies.html

**Comment by kadamwhite** [comment]
As a side node, `wp.users.me()` will retrieve the record for your user, once logged-in; `wp.posts().param('status', 'draft').etcetera` will not be chained off of the call to `.me()`.

**Comment by wblaircox** [comment]
@kadamwhite well that finally worked perfectly, once I made a few tweaks to my code - thanks!!!!!  I have custom fields I'm using to store my data in the posts. **I'm just trying to figure out where the custom fields are in the JSON returned**. Is there something else I need to do to get this to appear using node-wpapi? It was buried before in the Backbone structure.

Cheers!

**Comment by kadamwhite** [comment]
@wblaircox I'd check out [register_rest_field](http://v2.wp-api.org/extending/modifying/) to ensure those fields get included in the returned JSON. Hope that helps!

**Comment by wblaircox** [comment]
@kadamwhite  HA!!! that only took 2 weeks!!! But, I've learned a great deal around using WordPress for far more than I have in the past. Thank you very much for all your assistance - that article you wrote last night was the missing key to properly using this.
