### ISSUE TITLE
EndpointRequest customization

### ISSUE THREAD

**Issue by edygar** [WP-API/node-wpapi#211]
Could https://github.com/WP-API/node-wpapi/blob/master/lib/endpoint-factories.js#L41 refer to `handlers[ resource ].Ctor` instead directly to var EndpointRequest?

I need to inject some code before and after any of the `_httpMethod` are called but the way it is today, I would need to actually mutate each EndpointRequest instance where I could just inherit from them. Also,`invokeAndPromisify` been privated locks me of just overriding it.

Can somebody help me? My intention is to have access to the RequestData itself, so I could resolve locally when possible (as for local cache or optimistic updates)

**Comment by kadamwhite** [comment]
@edygar That sounds like it'd be a good idea, that would be a useful seam to introduce. Can you share some pseudocode of what you'd be hoping for, so I can make sure I understand your idea?

**Comment by kadamwhite** [comment]
Also, it sounds like what you're looking for is direct access to `WPRequest`, more than to the Ctors for the individual handlers -- is that an accurate assessment?

**Comment by edygar** [comment]
Just for context: I'm working on a Redux Middleware which needs to act between the query declaration and the request, if the data is already available, it should resolve the promise right alway, in case of data retrieval, or update local data, in case of mutations. 

> Also, it sounds like what you're looking for is direct access to WPRequest, more than to the Ctors for the individual handlers -- is that an accurate assessment?

@kadamwhite, yes, if I could just inject a WPRequest factory, it would solve my problem of access. Here's a very simplified pseudo-code to illustration such intervetion:

```js
_httpGet( callback = _.nthArg(0) ) {
  var cache = this._getCacheIfAvailable();
  if (cache) {
    return Promise.resolve(cache).then(callback);
  }
  return WPRequest._httpGet.call(this, result => {
    this._refreshCache(this, result);
    return result;
  }).then(callback);
};
```

**Comment by kadamwhite** [comment]
@edygar Thank you for clarifying, that makes a lot more sense. I'll look into it

**Comment by kadamwhite** [comment]
Consider whether providing customization of WPRequest can also become a vector for injecting handling for different authentication schemes

**Comment by kadamwhite** [comment]
@edygar I just opened #220 to attempt to provide an official way to modify the HTTP behavior; I would welcome your feedback on that API!

**Comment by edygar** [comment]
First of all, thank you! That's awesome!

I'm gonna take a look tomorrow and I give a proper feedback, but at first glance that's exactly what I asked for!
