### ISSUE TITLE
Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by preschian** [WP-API/node-wpapi#214]
dunno why i can't use this package
error when require/import the package

<img width="1226" alt="screen shot 2016-08-27 at 9 12 51 pm" src="https://cloud.githubusercontent.com/assets/734428/18027955/806cfcc6-6c9b-11e6-9489-8f8323e3d0b4.png">

**Comment by kadamwhite** [comment]
Either try to import the prebuilt bundle in /browser, or if you're using webpack add json-loader or if you're using browserify there should be a browserify transform. If that doesn't work let me know the details of your build and I'll take a deeper look!

**Comment by preschian** [comment]
ooppss, sorry... the problem is with the webpack instead
solved with json-loader

thank you~
webpack/webpack/issues/965
