### ISSUE TITLE
Unable to Create New Post

### ISSUE THREAD

**Issue by nodeGarden** [WP-API/node-wpapi#215]
I've tried the simpliest of examples in creating a post, and it keeps telling me: 
```JSON
{"code":"rest_cannot_create","message":"Sorry, you are not allowed to create new posts.","data":{"status":401}}
```
I have created a new user, reset the password multiple times, confirmed I can login and post through the UI, and re-installed both the `WP REST API` and the `JSON Basic Authentication` plugins multiple times.

```JavaScript
var WP = require( 'wpapi' );

var options = {
    "protocol" : "http:",
    "host" : "IP ADDRESS",
    "port" : "80",
    "path" : "/wp-json",
    "method" : "POST",
    "auth" : {
              "user": "USER",
              "password": "PASSWORD"
            }
};

var wp = new WP({
    endpoint: options.protocol + "//" + options.host + options.path,
    username: options.auth.user,
    password: options.auth.password,
    auth: true
});

var _p = wp.posts().create({
    title:'test',
    content:'test content'
  })
  .then(function(response){
    console.log("complete");
    console.log(response);
  })
  .catch(function(err){
    // handle error
    console.log("ERROR:");
    console.log(err.response.text);
  });
```

Versions:
  - Wordpress: `4.6`
  - Node: `6.3.0`
  - NPM: `3.10.7`
  - WP REST API: `2.0-beta13.1`
  - JSON Basic Authentication: `0.1`

All other plugins disabled, and a fresh install of Wordpress with updates made before installing plugins.

**Comment by kadamwhite** [comment]
Thanks for opening the issue, I'll try to reproduce when I'm back at a computer this evening. If you get to this before I do, can you try without the port and let me know what result you get?

**Comment by nodeGarden** [comment]
@kadamwhite The port isn't used. I only set it in the Options object because I originally started with just a `http.request()` call, and I like to keep config together at the top.

**Comment by nodeGarden** [comment]
Closing. Doesn't look as if `node-wpapi` is the problem. Looks like other people are having similar issue. Added a comment in `Basic-Auth`: https://github.com/WP-API/Basic-Auth/issues/35#issuecomment-242988435 .
