### ISSUE TITLE
Discover and security

### ISSUE THREAD

**Issue by ludoo0d0a** [WP-API/node-wpapi#216]
I cannot find a way to use a custom namespace AND authentication.

discover cannot accept authentication as parameter.
and I didn't find how to set username/password after discover.

thanks

**Comment by kadamwhite** [comment]
@ludoo0d0a Thanks for the bug report. I'm focusing on this library for the next week so I will attempt to address this as soon as I'm back from the weekend.

**Comment by kadamwhite** [comment]
Looking into this today; the likely solution (which will support multiple authentication mechanisms as well) will be to make `.auth` a method that can be called on the WP site instance object to set it for all future requests.

**Comment by kadamwhite** [comment]
@ludoo0d0a You should be able to use this pattern without any code updates, it should have been feasible before but wasn't documented:

```js
var apiPromiseWithAuth = WP.discover( url ).then(function( site ) {
  return site.auth({
    username: 'admin',
    password: 'password'
  });
});
apiPromiseWithAuth.then(function( site ) {
  // site authentication is now pre-configured
});
```
(you can use nonce-based auth too, not just basic auth username/password)

**Comment by ludoo0d0a** [comment]
Thanks for explanations! I will try !
