### ISSUE TITLE
401 error 

### ISSUE THREAD

**Issue by marcianosr** [WP-API/node-wpapi#228]
Hi, 

I'm testing the WP Node API and I'm trying to create a post, however I get this error: 

`{
  "code": "rest_cannot_create",
  "message": "Sorry, you are not allowed to create new posts.",
  "data": {
    "status": 401
  }
}`

I'm authenticating with my login for wordpress and testing it on localhost. This is the code: 

```
var WPAPI = require( 'wpapi' );

var wp = new WPAPI({
    endpoint: 'http://localhost/WordPressAPI/wordpress/wp-json',
    
    username: 'username',
    password: '--!',
    auth: true
})

var post = wp.posts().create({
    // "title" and "content" are the only required properties
    title: 'Your Post Title',
    content: 'Your post content',
    // Post will be created as a draft by default if a specific "status"
    // is not specified
    status: 'publish'
}).then(function( response ) {
    // "response" will hold all properties of your newly-created post,
    // including the unique `id` the post was assigned on creation
    console.log( response.id );
});
```

Running this code in NodeJS doesn't do anything either. Does someone know what I'm doing wrong? 
Thanks!

**Comment by kadamwhite** [comment]
Hello @marcianosr and thanks for using the WordPress REST API (and this library!) Can I ask whether you're running the [Basic Auth plugin](https://github.com/wp-api/basic-auth) on your site? That plugin must be installed and active for username/password authentication to succeed.

As a side note, the "auth: true" should be unnecessary, but would not contribute to the error you are seeing.

**Comment by marcianosr** [comment]
Hi @kadamwhite! 

Thanks for answering! 
Yes I downloaded the Basic Auth plugin on my website. I somehow still get a 401 error on creating posts. Pretty weird, maybe I missed something.

**Comment by kadamwhite** [comment]
@marcianosr May I ask what you're using to run your local server?

You can check to see if it's an issue with the client itself or an issue with your server by testing the request with `curl`; for my test environment if I run 

```sh
curl --user apiuser:password http://wpapi.loc/wp-json/wp/v2/users/me
```
I then get back the JSON for my user record, the same as if I ran
```js
require( 'wpapi' ).site( 'http://wpapi.loc/wp-json' ).auth({
  username: 'apiuser',
  password: 'password'
}).users().me().then(function( user ) {
  console.log( user );
});
```

If the `curl` command doesn't work (and curl should be available for all systems, how you install it depends on your operating system) then the issue is probably a server setting of some sort.

**Comment by marcianosr** [comment]
@kadamwhite 
I'm using wamp server for my wordpress configuration with a standard installed wordpress, and running another server on another port for the frontend and node js backend. 
When I cURL or use postman to the url, I get the same 401 error, while I am logged in to WordPress.

`{
  "code": "rest_not_logged_in",
  "message": "You are not currently logged in.",
  "data": {
    "status": 401
  }
}`

**Comment by marcianosr** [comment]
@kadamwhite 
I got it working! It seems I installed the wrong basic auth plugin... 
I now installed the good version: https://github.com/WP-API/Basic-Auth

Thanks  for helping :)

**Comment by kadamwhite** [comment]
@marcianosr my pleasure, I'm glad to hear you got things working! Thanks for the update and let us know if you run into anything else!
