### ISSUE TITLE
Document that it is possible to send a file using a buffer

### ISSUE THREAD

**Issue by Ohar** [WP-API/node-wpapi#245]
Or maybe is it planned to? 
I have file buffers and current API force me to save it on disk to `temp` folder, then upload it with by its disk path and then delete it. 
It is a thing I have a lot of problem to now.

**Comment by Ohar** [comment]
Oh its just works, I am an idiot.

**Comment by kadamwhite** [comment]
@Ohar If it wasn't clear that could be done, I don't think you're an idiot, I think our docs need improvement :) Thanks very much for the catch, and I'm glad to hear that it works!
