### ISSUE TITLE
Filtering posts by date, category, etc not working without `filter`

### ISSUE THREAD

**Issue by ryelle** [WP-API/node-wpapi#247]
Are there plans to update this library now that `filter` has been removed from the core API? I'm using this for [the theme on my site](https://ryelle.codes/), and can't display archive pages because they're requested using the filter param.

For example, `posts().category( 4 )` fetches `/posts?filter[cat]=4`, while it should be `/posts?categories=4`.

I'm happy to contribute code, too, if you point me in the right direction :)

**Comment by kadamwhite** [comment]
@ryelle thanks for using the library! There are plans to remove filter(), but since there are also plans to add that parameter back in as a plugin I may leave the code in here so that it can be used as a mixin. Id welcome your thoughts on that idea.

**Comment by kadamwhite** [comment]
This should be resolved in v0.12, now released

**Comment by kadamwhite** [comment]
Note that `.tags()` and `.categories()` is now preferable to `.tag()` and `.category()`, and that the slug-based querying supported by the latter will not work in 4.7
