### ISSUE TITLE
Update custom taxonomy collection documentation

### ISSUE THREAD

**Issue by joaojeronimo** [WP-API/node-wpapi#251]
I got `TypeError: wp.taxonomies(...).taxonomy(...).term is not a function`.

Am I missing anything ?

**Comment by joaojeronimo** [comment]
.terms also seems to not be a function.

`TypeError: wp.taxonomies(...).taxonomy(...).terms is not a function`

**Comment by joaojeronimo** [comment]
Although `wp.taxonomies().taxonomy('taxonomy_name', termIdentifier)` is working. Is that what it's supposed to be ?

**Comment by kadamwhite** [comment]
@joaojeronimo Thank you for catching this, that documentation is outdated. Term collections are now top-level routes on the `/wp/v2` namespace, and are no longer nested within their parent taxonomy. The result of this is that the nesting operators documented in the README are pointing to a route that no longer exists -- for the custom taxonomy "genre", for example, if registered

```php
	register_taxonomy( 'genre', array( 'album' ), array(
		'hierarchical'      => true,
		'show_ui'           => true,
		'show_admin_column' => true,
		'query_var'         => true,
		'rewrite'           => array( 'slug' => 'genre' ),
		'show_in_rest'      => true,
		'rest_base'         => 'genres',
		'rest_controller_class' => 'WP_REST_Terms_Controller',
	));
```
then running `wp.taxonomies().taxonomy('genre')` yields this object:
```js
{ name: 'Genres',
  slug: 'genre',
  description: '',
  types: [ 'album' ],
  hierarchical: true,
  rest_base: 'genres',
  _links: 
   { collection: [ { href: 'http://yoursite.com/wp-json/wp/v2/taxonomies' } ],
     'wp:items': [ { href: 'http://yoursite.com/wp-json/wp/v2/genres' } ],
     curies: [ { name: 'wp', href: 'https://api.w.org/{rel}', templated: true } ] } }
```
which points to the new location of the Genres collection, `/wp/v2/genres`.

To access this via the API, you have two options. First, autodiscovery should detect and bind to that collection automatically:

```js
WPAPI.discover('http://wpapi.loc')
  .then(wp => {
    // site client instance now has a "genres" method to query against that collection
    return wp.genres();
  });
```

Alternatively, you can make a function to query the genres manually using a [custom route handler](http://wp-api.org/node-wpapi/custom-routes/):

```js
wp.genres = wp.registerRoute( 'wp/v2', '/genres/(?P<id>)' );
```

I'm renaming this issue to capture the needed documentation updates.

**Comment by joaojeronimo** [comment]
Thanks :)
