### ISSUE TITLE
Add multiple status params to request?

### ISSUE THREAD

**Issue by subatomicceo** [WP-API/node-wpapi#252]
I have registered a custom route as suggested in the documentation and all works as expected. However, the response seems to be missing any posts that aren't set to a status of "publish". I tried to add multiple status params to the query but am not having much luck. Any feedback would be greatly appreciated, thanks!

Example:
```
var site = new WPAPI({ endpoint: 'http://www.yoursite.com/wp-json' });
site.myCustomResource = site.registerRoute( 'myplugin/v1', '/author/(?P<id>)' );
site.myCustomResource
  .auth()
  .param('context','edit')
  .param('status','pending')
  .param('status', 'publish')
  .then(function( res ) {
    console.log(res); // missing pending posts
  }).catch(function( err ) {
    console.log('err',err);
});
```

**Comment by kadamwhite** [comment]
Hey @subatomicceo, thanks for using node-wpapi! The way `.param` works is that it expects to be called once for each query parameter, and overwrites previously-provided values. The workaround for providing multiple values is to pass them as an array:

```js
// Last one wins:
wpapi.posts().param('status', 'publish').param('status', 'pending')
// http://my-site.com/wp-json/wp/v2/posts?status=pending

// Both parameters captured:
wpapi.posts().param('status', [ 'publish', 'pending' ])
// http://my-site.com/wp-json/wp/v2/posts?status[]=pending&status[]=publish
```

I hope this helps, and if you see a place the documentation could be improved to better call this out we should make this more clear.
