### ISSUE TITLE
Use create() to for a new custom post type entry 

### ISSUE THREAD

**Issue by bigandy** [WP-API/node-wpapi#275]
I have a custom post type "health" can I use wpapi to create a new health entry?
The cpt is accessible https://`<site-url>`/wp-json/bigandy/v1/health

**Comment by kadamwhite** [comment]
Hey @bigandy, thanks for trying this project! Custom post types are supported best through `.registerRoute()`, and there is a user guide here http://wp-api.org/node-wpapi/custom-routes/ that should get you started. Please leave a comment below if you have any further questions!

**Comment by kadamwhite** [comment]
Closed the issue as it isn't strictly speaking a bug, but we can continue conversation in this thread.

**Comment by kadamwhite** [comment]
To clarify, assuming that you can access resources by ID like a post,
```
site.health = site.registerRoute('bigandy/v1', '/health/(?P<id>\\d+)');
site.health().create({})... // create a health record
site.health().id( 7154 )... // get /bigandy/v1/health/7154
```
etcetera

**Comment by bigandy** [comment]
@kadamwhite thanks for the information. 

Perhaps I am doing something wrong on the WordPress end then. The "POST" method is not available when I go to https://big-andy.co.uk/wp-json/bigandy/v1. Do I need to enable something? Here is my WordPress cpt code : https://github.com/bigandy/big-andy.co.uk/blob/live/content/plugins/bigandy/cpts.php

**Comment by PavlosIsaris** [comment]
@kadamwhite I have a 'guest_request" custom post type.
I am trying to use wpapi to create a new health entry as following: 
`this.wp.myCustomResource = this.wp.registerRoute( 'guest_request', '/(?P<id>\\d+)' );`

and then:
`this.wp.myCustomResource().auth().create({});`

But I get an error:
`error custom post Error: Invalid path component: (?P<id>\d+) does not match (?P<id>\d+)`

What am I doing wrong?
