### ISSUE TITLE
Auto discovery fail

### ISSUE THREAD

**Issue by stevengeorgeharris** [WP-API/node-wpapi#276]
I'm getting the following error when I start my Node application, my wordpress install is in a Docker container, running `wget nginx://` inside the Node container downloads the WordPress homepage fine.

```
Autodiscovery failed
{ [Error: cannot GET / (403)]
  status: 403,
  text: '<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n
<hr><center>nginx/1.10.2</center>\r\n</body>\r\n</html>\r\n',
  method: 'GET',
  path: '/' }
```

I'm wondering if anyone has come across this issue?

**Comment by kadamwhite** [comment]
Can you clarify the point at which the error occurs? Is it happening during the call to .discover(), or later on? What error is being logged from the JavaScript side?

**Comment by kadamwhite** [comment]
@stevengeorgeharris what ended up being the solution, if I may ask?

**Comment by stevengeorgeharris** [comment]
@kadamwhite I now believe the issue was unrelated to `node-wpapi`, in our Makefile we install and activate our wp plugins (endpoints) - just to test, we run the command again and voila! everything worked. 

To cut a long answer short - we believe it was a cache/nginx issue.

A very unique issue!

**Comment by kadamwhite** [comment]
@stevengeorgeharris Thanks for elaborating, and I'm glad to hear things worked out!
