### ISSUE TITLE
Troubleshooting Error

### ISSUE THREAD

**Issue by idevwebs** [WP-API/node-wpapi#281]
Hi there.

I'm trying to use this in a project and when I try to chain things together, I get an error such as:

Running:

`wp.posts().filter({
    category_name: 'islands',
    tag: [ 'clouds', 'sunset' ]
}).get();`

I get:

Error: wp.posts().filter is not a function. (In 'wp.posts().filter({
    category_name: 'islands',
    tag: [ 'clouds', 'sunset' ]
})', 'wp.posts().filter' is undefined)

Yet if I run:

`wp.types().type( 'mytype' ).get(function( err, data ) {
    if ( err ) {
        // handle err
    }
    console.log(JSON.stringify(data, null, 4));
});`

I get the properties in console.

Why is this?

**Comment by kadamwhite** [comment]
What version of the API are you using, the beta rest-api plugin or 4.7? If 4.7, are you using the rest-filter plugin? The "filter" parameter was removed in WordPress 4.7. Let me know and I'll see what I can do to advise

**Comment by kadamwhite** [comment]
Closing due to lack of response; installing the https://github.com/wp-api/rest-filter plugin may resolve the issue, if dependence on `?filter` cannot be avoided.
