### ISSUE TITLE
posts().create().then() returns empty response

### ISSUE THREAD

**Issue by Sphmer** [WP-API/node-wpapi#282]
Hi there. First of all thank you for your work.
I'm runnin both apache with wordPress 4.7 and my nodeJS server localy.
When I'm trying to create a post like (I'm using basic authintication):

```
        var WPAPI = require('wpapi');
        var wp = new WPAPI({
            endpoint: 'http://localhost/wp-json',
            username: '***',
            password: '***'
        });

        wp.posts().create({
            title: 'Your Post Title',
            content: 'Your post content',
            status: 'publish'
        }).then(function( response ) {
            console.log(arguments);
        });
```

it creates correct post, but not returns any parameters of created item, like ID and so on.....
here is nodejs console output:
`{ '0': {} }`

i'm using node.js version = v6.2.1

**Comment by kadamwhite** [comment]
This sounds like a very interesting bug! Could you try to create the post using curl, from the command line (or using a direct request from a JS library like request, axios or superagent) and let me know what result you get?

**Comment by Sphmer** [comment]
Seems like false alarm.
Wrong settings in my php.ini cause appearance of error in WordPress response:
`<br />
<b>Deprecated</b>:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in <b>Unknown</b> on line <b>0</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Unknown</b> on line <b>0</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api\class-wp-rest-server.php</b> on line <b>1244</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api.php</b> on line <b>516</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api.php</b> on line <b>517</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api.php</b> on line <b>518</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script><br />
<b>Warning</b>:  Cannot modify header information - headers already sent in <b>Z:\home\localhost\www\wp-includes\rest-api.php</b> on line <b>519</b><br />
<script language=JavaScript src='/denwer/errors/phperror_js.php'></script>{"id":11,"date":"2016-12-28T10:26:16","date_gmt":"2016-12-28T05:26:16","guid":{"rendered":"http:\/\/localhost\/2016\/12\/28\/your-post-title-324234234\/","raw":"http:\/\/localhost\/2016\/12\/28\/your-post-title-324234234\/"},"modified":"2016-12-28T10:26:16","modified_gmt":"2016-12-28T05:26:16","password":"","slug":"your-post-title-324234234","status":"publish","type":"post","link":"http:\/\/localhost\/2016\/12\/28\/your-post-title-324234234\/","title":{"raw":"Your Post Title 324234234","rendered":"Your Post Title 324234234"},"content":{"raw":"Your post content","rendered":"<p>Your post content<\/p>\n","protected":false},"excerpt":{"raw":"","rendered":"<p>Your post content<\/p>\n","protected":false},"author":1,"featured_media":0,"comment_status":"open","ping_status":"open","sticky":false,"template":"","format":"standard","meta":[],"categories":[1],"tags":[],"_links":{"self":[{"href":"http:\/\/localhost\/wp-json\/wp\/v2\/posts\/11"}],"collection":[{"href":"http:\/\/localhost\/wp-json\/wp\/v2\/posts"}],"about":[{"href":"http:\/\/localhost\/wp-json\/wp\/v2\/types\/post"}],"author":[{"embeddable":true,"href":"http:\/\/localhost\/wp-json\/wp\/v2\/users\/1"}],"replies":[{"embeddable":true,"href":"http:\/\/localhost\/wp-json\/wp\/v2\/comments?post=11"}],"version-history":[{"href":"http:\/\/localhost\/wp-json\/wp\/v2\/posts\/11\/revisions"}],"wp:attachment":[{"href":"http:\/\/localhost\/wp-json\/wp\/v2\/media?parent=11"}],"wp:term":[{"taxonomy":"category","embeddable":true,"href":"http:\/\/localhost\/wp-json\/wp\/v2\/categories?post=11"},{"taxonomy":"post_tag","embeddable":true,"href":"http:\/\/localhost\/wp-json\/wp\/v2\/tags?post=11"}],"curies":[{"name":"wp","href":"https:\/\/api.w.org\/{rel}","templated":true}]}}`

after changing always_populate_raw_post_data to -1 in php.ini everything works fine))
