### ISSUE TITLE
How to fetch posts of custom post type?

### ISSUE THREAD

**Issue by arturgithub** [WP-API/node-wpapi#283]
Hi there, first of all thank your very much for the project!!

I have no clue about how to query custom post types. In my reactjs app, all the code you put in the documentation works fine. But I cannot find a sample of querying custom post types that I can replicate.

I would appreciate any sample (I cannot get https://github.com/WP-API/WP-API/issues/1299 to work:)

**Comment by sdgluck** [comment]
The link you shared concerns the Backbone client, which has a different API to this one (`node-wpapi`).

To query a custom post type you first have to register it with your instance by using the `registerRoute` method. You can then assign the result of this call to a property on the instance for ease of access.

For example, to register a custom post type "Article":

1. Register the custom post type with your instance.

        var namespace = 'wp/v2'; // use the WP API namespace
        var route = '/articles/(?P<id>)'; // route string - allows optional ID parameter

        wpapi.articles = wpapi.registerRoute(namespace, route);

2. Consume the custom post type:

        wpapi.articles().get() // get all Articles

You can find more information about consuming custom post types in [the documentation](https://github.com/WP-API/node-wpapi#custom-routes), including how to add [additional filtering functionality](https://github.com/WP-API/node-wpapi#query-parameters--filtering-custom-routes).

Happy holidays!

**Comment by arturgithub** [comment]
Thank you @sdgluck !!!!

**Comment by sunpietro** [comment]
Hi,
I have a custom post that has a `post_type` of `sp_player`. 

I did something like this:
```
const namespace = 'wp/v2';
const playersRoute = '/players/(?P<id>)';

wpapi.players = wpapi.registerRoute(namespace, playersRoute);
```

And I'm getting the `rest_no_route` error. What causes that?
I'm using Wordpress 4.7.3

**Comment by sdgluck** [comment]
@sunpietro Are you sure that `players` is the right slug for your post type?

**Comment by kadamwhite** [comment]
Alternatively, you can provide `players` as the "rest_base" property when registering your post type, which will change where the collection is exposed. Hope this helps

**Comment by sunpietro** [comment]
@kadamwhite after further investigation I found out that I missed REST endpoints exposure. So I exposed them in the `functions.php`.
I think, this is very important but missing information in the `node-wpapi` doc.
