### ISSUE TITLE
GET requests for collections require authentication?

### ISSUE THREAD

**Issue by photocurio** [WP-API/node-wpapi#284]
I'm trying to build an app that only uses GET requests. The client and server are on different subdomains, so I added this to the htaccess on the WP server:
`<IfModule mod_headers.c>
Header set Access-Control-Allow-Origin "*"
Header set Access-Control-Allow-Credentials "false"
</IfModule>`

In my app, I have no trouble getting _single_ posts and pages with requests like this:
`wp.pages().id(18633).then(function(data) {
	foundationPage = data;
});`.

But when I try to get a collection of posts in a category, with a request like this:
`wp.posts().param('categories', 989).then(function(data) {
	foundationPosts = data;
});`
The request returns an empty array.  There is no error: the response is a 200. But there is no data in the array.  But if I pass a username and password, I do get the data!  

The reason I don't like this is that authentication triggers a _preflight request_, and that makes for long response times. Anyway, I thought authentication isn't necessary for GET requests. 

So, how can I get collections without authentication?

**Comment by kadamwhite** [comment]
Hello @photocurio, thanks for the question! Collection requests should not require authentication; the request should work as you describe, e.g. http://demo.wp-api.org/wp-json/wp/v2/posts?categories=7

If you're seeing an empty array, then my first suspicion is that the category ID is invalid; the posts endpoint will return an empty array if it is asked for a category that does not exist. To dig in a little further, a few questions: What version of the API are you using, a beta from Github or the built-in WordPress 4.7 endpoints? Are you certain category 989 exists? What do you get when you log `wp.posts().param('categories', 989).toString()`?

**Comment by photocurio** [comment]
Kadam, thanks for the quick reply. 

I'm using the WP 4.7 endpoints, and yes, category 989 exists.  If I use your log idea, I get this url:
`http://devtesla.corp.com/wp-json/wp/v2/posts?categories=989` (a dev server behind a corporate firewall).

If I open this URL in a new tab, I see an array of ten post objects.

_But if I log out of the WordPress instance_, and reload, I see an empty array. Just two square brackets!

And then, if I go to the endpoint for a single post or a page, I see the whole data object, even when I'm logged out.  Weird.  So I don't think this is a problem with wpapi.  If you want to close this issue, I'll open one on the WordPress forum.

**Comment by kadamwhite** [comment]
That's fascinating! Sorry to hear the problem persists, hope you get it sorted and good luck figuring it out! I'll close this but if you do figure out a solution I'd be interested to hear it :)

**Comment by photocurio** [comment]
thread is here: if you want to follow:
https://wordpress.org/support/topic/get-requests-to-the-wp-api-requires-authentication/
