### ISSUE TITLE
how to set post_meta when creating a post?

### ISSUE THREAD

**Issue by jiji262** [WP-API/node-wpapi#286]

**Comment by emreycolakoglu** [comment]
I'd like to learn this as well. Currently I'm trying like
```
meta: [{
            key: 'external_thumbnail',
            value: thumbnail
        }]
```
while creating posts, but no luck

**Comment by chattes** [comment]
Even I have the same issue any ideas how can we update Meta Fields?

**Comment by kadamwhite** [comment]
How are you registering the meta you wish to update?

**Comment by kadamwhite** [comment]
If you use `register_rest_field` like this: https://github.com/kadamwhite/wp-notebook/blob/master/wp-notebook.php#L62-L81 then you should be able to update the value by passing that key in the response: https://github.com/kadamwhite/wp-notebook/blob/master/src/components/EntryComposer/index.jsx#L49-L53

**Comment by kadamwhite** [comment]
If you're using `register_meta`, it should be something like this (untested):

```
meta: {
    external_thumbnail: thumbnail
}
```

**Comment by kadamwhite** [comment]
cc @jiji262 / @emreycolakoglu

**Comment by jamesjara** [comment]
What about with https://codex.wordpress.org/Function_Reference/update_post_meta  I have a big problem using this plugin and framework... documentations is missing or not working.. hard to debugg, thanks for your help

**Comment by kadamwhite** [comment]
Closing this as a duplicate of #280 to unify the threads; meta handling is currently our top-priority documentation issue
