### ISSUE TITLE
Documentation: 'Manually forcing authentication' wrong examples

### ISSUE THREAD

**Issue by gambry** [WP-API/node-wpapi#289]
The example for manually specifying username and password as part of a request chain for Basic Authentication is (probably) wrong:
```
// Use username "mcurie" and password "nobel" for this request
wp.posts().id( 817 ).auth( 'mcurie', 'nobel' ).get(...
```

While the right code working for me is:
// Use username "mcurie" and password "nobel" for this request
```
// Use username "mcurie" and password "nobel" for this request
wp.posts().id( 817 ).auth( {username: 'mcurie', password: 'nobel'} ).get(...
```

Happy to propose a PR if my point is correct.

**Comment by kadamwhite** [comment]
You are correct, the `(name, pass)` syntax should be obsolete now. A PR would be welcomed!
