### ISSUE TITLE
Documentation Error: Cookie Auth Example 

### ISSUE THREAD

**Issue by bkirby989** [WP-API/node-wpapi#293]
http://wp-api.org/node-wpapi/authentication/#cookie-authentication

The above example uses `get_json_url()` and `wp_json` for script localization.

These values should be`rest_url()` and `wp_rest`, respectively. ``

**Comment by bkirby989** [comment]
Also that section links to http://wp-api.org/guides/authentication.html which appears to be deprecated and contains the same error. It should probably link to https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

**Comment by kadamwhite** [comment]
Aha, thanks for this catch! I'll upgrade this week, and get this out during LoopConf.

**Comment by kadamwhite** [comment]
Managed to sneak this out with v1.0.2 tonight, thanks again for calling out the issue @bkirby989 !

**Comment by bkirby989** [comment]
Of course, thanks for the timely fix!
