### ISSUE TITLE
Optional logging?

### ISSUE THREAD

**Issue by sdgluck** [WP-API/node-wpapi#295]
When a request 404s `superagent` will say "Error: Not Found", and isn't kind enough to tell us what it didn't find... In our applications we have had to copy/paste `node-wpapi`'s own transport API to add logging that tells us the URL of a request before it dispatches. 

Ideally this could be option within the library itself, e.g. `debug` option that defaults to false and is picked up in transport methods like this:

```
function _httpGet( wpreq, callback, debug ) {
    if ( debug ) {
        console.log( '[node-wpapi] GET ' + wpreq.toString() );
    }
    
    checkMethodSupport( 'get', wpreq );
    // ...
}
```

Are you happy for me to put in a PR for this?

**Comment by kadamwhite** [comment]
@sdgluck That's a pretty good idea, I'd definitely be interested in adding this. I'd probably want to read the "debug" option off of the WPReq instance, so that it can be set for a full bound WPAPI instance or for a specific instantiated WPRequest; I'd also lean towards giving the transport itself a `debug()` method that can be injected so that users can self-select for `console.log`, or something like morgan that could integrate with their server logs, etc.

**Comment by kadamwhite** [comment]
@sdgluck I'm unlikely to have time to prototype this over the coming weeks but I'm still interested in the idea. If you have time to submit a PR I'd love to see this move forward; if not I should get to it later in the summer.

**Comment by sdgluck** [comment]
@kadamwhite Sorry- didn't see your comment until now. I might have some time to have a go at this in the next week or two. 👍 If not, I'll let you know.

**Comment by amitsarangi** [comment]
Any progress ? I can create a PR for it.

**Comment by sdgluck** [comment]
@amitsarangi No, please go ahead!

**Comment by amitsarangi** [comment]
@sdgluck @kadamwhite I had a look into it last weekend. But was confused what's the best way to approach. One option is to pass a `debug` flag through the instance, which if passed to the WPAPI instance, we can format and print the log (similar to the code snippet in the beginning of the discussion ). The other option was to pass a superagent middleware like superagent-logger. What would be the preferred way ?

**Comment by kadamwhite** [comment]
A debug flag has the advantage of becoming part of a defined public API that can be used with multiple transport layers.
If we went the superagent middleware approach, more change would be required if we migrate to a different HTTP transport layer; however, in the meantime it would be pretty straightforward (he says, not having tried it...) to put together a replacement HTTP transport that could be used with the library as-is.

**Comment by kadamwhite** [comment]
I'm going to roll this into #324 — if we have a generic hook which receives the WPRequest object and the transport object or configuration before it is sent, logging can be introduced in that seam.
