### ISSUE TITLE
Requests in an interval return cached results

### ISSUE THREAD

**Issue by andreasvirkus** [WP-API/node-wpapi#298]
Hi,

I'm polling a Wordpress site's multiple REST endpoints and the subsequent requests don't seem to make it to the Wordpress side (access.log file remains empty after the first requests).

All relavant files:
https://gist.github.com/andreasvirkus/9c413339d8854e0bb98bc62fa35e0cae

**Comment by kadamwhite** [comment]
@andreasvirkus It looks like the code here is only designed to initiate the request once. Looking at this method, for example:
```js
export const getPages = wp.pages()
  .param('per_page', '80')
  .param('timestamp', Date.now()).then((response) => {
    return response;
  }).catch((err) => {
    console.log('ERR! Could not retrieve pages:', err);
  });
```
this initiates a request and exports a single Promise that will resolve to its results. Importing or referencing `getPages` again will return that same Promise reference; it will not trigger a new request.

I recommend refactoring the exports of queries.js to be methods that return promises:
```js
// Adds () => to the assignment to make getPages a function, not a Promise
export const getPages = () => wp.pages()
  .param('per_page', '80')
  .param('timestamp', Date.now()).then((response) => {
    return response;
  }).catch((err) => {
    console.log('ERR! Could not retrieve pages:', err);
  });
```
If you do that, and then call `getPages()`, it will trigger a new request.

Hope this helps

**Comment by kadamwhite** [comment]
To make `pages.all = getPages()` work, too, you'd either need to change that to

```
getPages().then(result => {
  pages.all = result;
});
```
or else use async/await (available in the latest Node 7, I believe)
```
pages.all = await getPages()
```
