### ISSUE TITLE
\node_modules\wpapi\lib\http-transport.js: Module does not exist in the module map or in these directories:

### ISSUE THREAD

**Issue by geekeren** [WP-API/node-wpapi#300]
when add this library into my React Native project,,these is an error when I start ReactNative server:

>Unhandled promise rejection (rejection id: 797): UnableToResolveError: Unable to resolve module url from E:\AndroidProject\RNBlog\ReactNative\node_modules\wpapi\lib\http-transport.js: Module does not exist in the module map or in these directories:
E:\AndroidProject\RNBlog\ReactNative\node_modules\wpapi\node_modules
, E:\AndroidProject\RNBlog\ReactNative\node_modules
Anyone know why?

**Comment by kadamwhite** [comment]
What version of NPM are you using?

**Comment by geekeren** [comment]
@kadamwhite 4.1.2

**Comment by kadamwhite** [comment]
Possibly related: facebook/react-native#7686

I'm tied up at a conference today but can take a look at this by tomorrow afternoon if it doesn't sort itself our

**Comment by geekeren** [comment]
@kadamwhite I do as your suggestion but it doesn't work, then I install wpapi and react-native on ubuntu system,the error occured ,too,like Windows system

**Comment by geekeren** [comment]
waiting for solution of this issue

**Comment by geekeren** [comment]
This issue has been solved:when using this client in react-native project, the dependency of    **url** and **util** is required.you can add dependencies in  **package.json** like this:
```
  "dependencies": {
    "react": "16.0.0-alpha.6",
    "react-native": "0.43.4",
    "react-native-menu": "^0.20.2",
    "url": "^0.11.0",
    "util": "^0.10.3",
    "wpapi": "^1.0.3"
  },
```
