### ISSUE TITLE
Autodiscovery failed: No header link found with rel="https://api.w.org/"

### ISSUE THREAD

**Issue by entr** [WP-API/node-wpapi#303]
I'm just starting with the whole REST thing but this one just felt like it's not me doing something stupid, or is it?

What I am doing simply is:

```js
  let discovery = WPAPI.discover('http://wp.dev')

  discovery.catch(function (e) {
    console.error(e)
  })
```

First I had the super annoying CORS issue. No problem, found this little plugin https://github.com/ahmadawais/WP-REST-Allow-All-CORS/blob/master/plugin.php but of no avail, for discovery at least - `rest_api_init` is never fired for discovery HEAD requests.

So I threw some more code:
```php
add_action( 'send_headers', function() {
	if ( ! did_action('rest_api_init') && $_SERVER['REQUEST_METHOD'] == 'HEAD' ) {
		header("Access-Control-Allow-Origin: *");
		header("Access-Control-Allow-Methods: HEAD");
	}
} );
```
Now, no CORS problems for HEAD but `WPAPI.discover()` is failing with:

```
Error: No header link found with rel="https://api.w.org/"
    at locateAPIRootHeader (eval at <anonymous> (app.js:2217), <anonymous>:24:8)
    at tryCatch (eval at <anonymous> (app.js:1919), <anonymous>:410:12)
    at invokeCallback (eval at <anonymous> (app.js:1919), <anonymous>:425:13)
    at publish (eval at <anonymous> (app.js:1919), <anonymous>:393:7)
    at MutationObserver.flush (eval at <anonymous> (app.js:1919), <anonymous>:121:5)
(anonymous) @ wpapi.js?c140:425
tryCatch @ es6-promise.js?c993:410
invokeCallback @ es6-promise.js?c993:425
publish @ es6-promise.js?c993:393
publishRejection @ es6-promise.js?c993:335
flush @ es6-promise.js?c993:121

wpauth.js?9cc1:10 Error: Autodiscovery failed
    at eval (eval at <anonymous> (app.js:2328), <anonymous>:431:10)
    at tryCatch (eval at <anonymous> (app.js:1919), <anonymous>:410:12)
    at invokeCallback (eval at <anonymous> (app.js:1919), <anonymous>:425:13)
    at publish (eval at <anonymous> (app.js:1919), <anonymous>:393:7)
    at publishRejection (eval at <anonymous> (app.js:1919), <anonymous>:335:3)
    at MutationObserver.flush (eval at <anonymous> (app.js:1919), <anonymous>:121:5)
(anonymous) @ wpauth.js?9cc1:10
tryCatch @ es6-promise.js?c993:410
invokeCallback @ es6-promise.js?c993:425
publish @ es6-promise.js?c993:393
publishRejection @ es6-promise.js?c993:335
flush @ es6-promise.js?c993:121
```
How come?

**Comment by entr** [comment]
Turns out I needed one more access-control header to instruct browser not to ignore custom headers. https://github.com/visionmedia/superagent/issues/713 helped me realize that. Providing `Access-Control-Expose-Headers` did it. My `send_headers` hook now is:

```php
add_action( 'send_headers', function() {
	if ( ! did_action('rest_api_init') && $_SERVER['REQUEST_METHOD'] == 'HEAD' ) {
		header("Access-Control-Allow-Origin: *");
		header("Access-Control-Expose-Headers: Link, X-WP-Nonce");
		header("Access-Control-Allow-Methods: HEAD");
	}
} );
```
Additionally I also expose `X-WP-Nonce` because WP is sending nonce back for further requests.
Hope this is useful for others.

**Comment by kadamwhite** [comment]
Re-opening so I remember to capture that in the documentation: thanks for the update!

**Comment by adamplabarge** [comment]
Was getting same error, followed the instructions to add headers hook and even the CORES plugin - still nothing.

Add /wp-json/ to the URI and it works.  would be nice to get the docs at http://wp-api.org/node-wpapi/using-the-client/ to reflect that.
