### ISSUE TITLE
How to request 'forgot password' and 'reset password' action

### ISSUE THREAD

**Issue by pietrasiak** [WP-API/node-wpapi#304]
I was checking `wpapi.users()` functions and prototype, but could not find anything like that. Is it possible with this library?

If no, any recommendation, how to add it or handle such request without rewriting rest client?

**Comment by kadamwhite** [comment]
@pietrasiak thanks for your question. Unfortunately setting or re-setting passwords is not something that should be done via the REST API; accounts should be created via the WordPress admin or on the site server with WP CLI. This is not something we will be providing endpoints for. 

Hope that helps clarify things; I'm going to close this issue but please respond below if you have further questions.
