### ISSUE TITLE
Syntax error with forward slash in group pattern

### ISSUE THREAD

**Issue by obenland** [WP-API/node-wpapi#310]
This should be reproducible on every site with Jetpack enabled.

The Plugin Directory v3 (and Jetpack) include forward slashes in some of their route group patterns:
```
"/jetpack/v4/plugin/(?P<plugin>[a-z\\/\\.\\-_]+)"
```

It looks like these forward slashes get removed when [the route tree gets broken down](https://github.com/WP-API/node-wpapi/blob/043a0622277003d05e1e015d7e6c133db966fcb0/lib/route-tree.js#L143), resulting in an invalid regex.

**Comment by kadamwhite** [comment]
This feels tricky to handle because there is a pretty deep assumption in our route parsing that a forward slash indicates a hierarchical level of the route, and would not occur in a regex. I will look into it, but would also welcome your input on how to resolve the situation.

**Comment by kadamwhite** [comment]
@obenland It wasn't as deeply engrained into the logic as I had thought, and #318 is now up for review -- if you have the opportunity to review or test that PR out I'd love your eyes
