### ISSUE TITLE
How to set an authorisation header?

### ISSUE THREAD

**Issue by andreasvirkus** [WP-API/node-wpapi#312]
Hi. I'm most likely getting something very basic wrong, but I can't put my finger on it.
I've got a JWT token that I'd like to set for my requests but superagent's `set` doesn't seem to work. Currently I get the following error:

`TypeError: _endpoints2.default.pages(...).set is not a function`

How would I go about setting the token? I saw `headers` in the docs, would that be it (and does it take an `Object` or something else)? Is there a way to set it for all requests by default (a custom transport maybe)?

```
import wp from './endpoints'; // I just export a new WPAPI() with some custom endpoints
import AuthService from './AuthenticationService';

let token = '';

AuthService.getAccessToken().then(webToken => {
    token = webToken;
});

export const getPages = () => wp.pages()
  .set('Authorization', 'Bearer ' + token)
  // .headers('Authorization', 'Bearer ' + token)  // How would the headers() format look?
  .param('per_page', '80')
  .then(response => {
    return response;
  }).catch(err => {
    console.log('ERR! Could not retrieve pages:', err);
  });
```

**Comment by andreasvirkus** [comment]
I think I got it working now with
```
wp.pages()
  .param('per_page', '80')
  .headers({ authorization: 'Bearer ' + token })
  .then(...);
```
But the request performed is now HEAD instead of GET, so the response body is missing.
In comparison, I've added a request for a custom endpoint where I didn't set the headers (remains of type GET)
```
172.018.000.001.36448-172.018.000.003.08080: HEAD /wp-json/wp/v2/pages?per_page=80 HTTP/1.1
Host: localhost:1234
User-Agent: node-superagent/3.5.2
Connection: close

172.018.000.001.36454-172.018.000.003.08080: GET /wp-json/wp-api-menus/v2/menu-locations/primary HTTP/1.1
Host: localhost:1234
Accept-Encoding: gzip, deflate
User-Agent: node-superagent/3.5.2
Connection: close
```

**Comment by mzalewski** [comment]
Alternatively, look at this pull request: https://github.com/WP-API/node-wpapi/pull/299
It's definitely cleaner than a new transport, but you'll have to use the forked version (until the pull request is merged)

**Comment by andreasvirkus** [comment]
Excellent, thank you so much for pointing me towards that PR, @mzalewski. And sorry for hunting you down like that 😄

**Comment by mzalewski** [comment]
No problem, happy to help - let me know if you have any issues

**Comment by andreasvirkus** [comment]
@mzalewski Gonna poke you once more... Does it matter if I assign the JWT to the WP
instance:
```

const WP = new WPAPI({
  endpoint: process.env.WP_ENDPOINT,
  jwt: token
});
```
or if I attach it to every request (since I might not have it when creating the instance):
```
wp.pages()
  .param('per_page', '80')
  .auth({ jwt: token })
  .then(response => {
    return response;
  });
```

**Comment by kadamwhite** [comment]
Hey y'all, apologies for letting this sit so long without response. We're evaluating supporting JWT natively but I will also be working on an update that includes a new method to set the headers to use on your request, which should make third-party support for JWT and other header-based authentication schemes much easier. I'll drop the PR link here for comments once I have something ready

**Comment by mzalewski** [comment]
That's great news :+1: 

@andreasvirkus I wouldn't think that you'd need to set it instance-wide - I haven't really tested it out though, so that's just based on my quick look at the pull request.

**Comment by kadamwhite** [comment]
@mzalewski @andreasvirkus I've proposed a system for specifying custom headers in pull request #315 and I would welcome your feedback on the implementation and interface.
