### ISSUE TITLE
Sorry, you are not allowed to create posts as this user - Auth issue

### ISSUE THREAD

**Issue by awcoding** [WP-API/node-wpapi#313]
My "app":

```js
#!/bin/env node
var WPAPI = require('wpapi');
var myusername = 'xxx';
var mypassword = 'xxx';

//var wp = new WPAPI({ endpoint: 'http://site.org:8080/wp-json', username:myusername, password:mypassword });
//
var api = WPAPI.discover( 'http://site.org:8080' ).then(function( site ) {
    return site.auth({
        username: myusername,
        password: mypassword
    });
});
api.then(function (wp) {

wp.posts().create({
    title: 'Your Post Title',
    content: 'Your post content',
    status: 'publish'
}).then(function( response ) {
    console.log( response.id );
}).catch (function(e) {
        console.log(e);
});
});
```

Gives me:
```shell
{ code: 'rest_cannot_create',
  message: 'Sorry, you are not allowed to create posts as this user.',
  data: { status: 401 } }
```

**Comment by awcoding** [comment]
Tried this with combos of: regular user + admin + concurrent login session web + logged out. No change.

**Comment by kadamwhite** [comment]
There doesn't appear to be anything wrong with your code; are you sure you have the [Basic Authentication plugin](https://github.com/wp-api/basic-auth) installed & activated? Only cookie authentication is enabled by default, other authentication schemes require a specific plugin to be installed.

If you've already got that running and you still encounter this issue write back here and I'll do what I can to help troubleshoot.

**Comment by awcoding** [comment]
I didn't have it installed. Thanks for letting me know.

**Comment by AnnieAnitha** [comment]
I am also having the same issue even after installing and activating the Basic Auth Plugin. All I want is to upload an image  via Wordpress REST api v2 .

POST Request:
http://localhost/wp-json/wp/v2/media
Authorization: Basic d29yZHByZXNzOndvcmRwcmVzcw==
Content-Type: image/jpeg
Content-Disposition: attachment;filename=map2.jpg

{
  "source_url" : "file:///home/Annie.Alfred/wallp/map2.jpg"
}

The header is : 
Access-Control-Allow-Credentials →true

Access-Control-Allow-Headers →Authorization, Content-Type

Access-Control-Allow-Methods →OPTIONS, GET, POST, PUT, PATCH, DELETE

Access-Control-Allow-Origin →

Access-Control-Expose-Headers →X-WP-Total, X-WP-TotalPages

Allow →GET

Connection →Keep-Alive

Content-Length →120

Content-Type →application/json; charset=UTF-8

Keep-Alive →timeout=5, max=100

Server →Apache/2.4.18 (Ubuntu)

Vary →Origin

X-Content-Type-Options →nosniff

X-Robots-Tag →noindex

The Response is:
{
    "code": "rest_cannot_create",
    "message": "Sorry, you are not allowed to create posts as this user.",
    "data": {
        "status": 401
    }
}

**Comment by Al2a2d2m** [comment]
First, check your .htacces to add these lines 
`RewriteEngine on
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`
Important: Restart your apache.
Important 2: Sometimes when you install somme plugins, .htacces file can be altered.

**Comment by kierahowe** [comment]
I just had almost exactly the same problem, trying to add something through REST API.   The trick is that you need to send the REST WP Nonce (named wp_rest) through with the request, as either a header, or as part of the request variable...  

if you use fetch, you can do this...
```
fetch( route, {
	method: method, 
	headers: {
		'X-WP-Nonce': wpApiSettings.nonce
	}
} )
```
or add it to your query vars as '_wpnonce'

You can find the code that is setting the current user to 0 at wp-includes/rest-api.php on line 834 (ver 5.2.1)

**Comment by Jerseynumber07** [comment]
> There doesn't appear to be anything wrong with your code; are you sure you have the [Basic Authentication plugin](https://github.com/wp-api/basic-auth) installed & activated? Only cookie authentication is enabled by default, other authentication schemes require a specific plugin to be installed.
> 
> If you've already got that running and you still encounter this issue write back here and I'll do what I can to help troubleshoot.

Yes, still facing issue

**Comment by ailishmc** [comment]
Nothing worked for me - I tried every plugin and variation of .htaccess! Then I found [this plugin](https://plugins.miniorange.com/wordpress-rest-api-basic-authentication-method). Absolute lifesaver! Hope it helps someone else.

**Comment by robertegj** [comment]
This is now built into the core Wordpress functionality, no plugins needed. 

Just go to Users -> Select the User -> Generate Application Password

You can now use that in combination with your username to make posts via the Wordpress API.

**Comment by ailishmc** [comment]
> This is now built into the core Wordpress functionality, no plugins needed.
> 
> Just go to Users -> Select the User -> Generate Application Password
> 
> You can now use that in combination with your username to make posts via the Wordpress API.

Thank you! I will flag this in the documentation as it doesn't make it super clear.
