### ISSUE TITLE
How to get specific page or post and corresponding next or previous

### ISSUE THREAD

**Issue by josephdburdick** [WP-API/node-wpapi#320]
Hello, I really appreciate the work put into this project! I was wondering how one would tackle requesting a specific post or page and then the next/previous result of that item? I've done this with search results but didn't know how/if it would work for a result from a specific ID or slug?

**Comment by kadamwhite** [comment]
Hello! @josephdburdick That's an interesting question. The API does not provide `prev` and `next` link headers for individual posts, so there is not an easy way to step forward and back between individual posts. The best I could offer would be to build an ordered list of post IDs or Slugs within your application and to use that to handle requesting the preceding or following post.

I'm going to close this issue as it's a drawback of the REST API itself; if it's something you're interested in seeing added I'd encourage you to submit a ticket at core.trac.wordpress.org and we will discuss making the change at the WordPress level. Thanks for using the REST API!

**Comment by josephdburdick** [comment]
That makes sense. Thanks, @kadamwhite.
