### ISSUE TITLE
401 Error - Rest Cannot Create

### ISSUE THREAD

**Issue by motleydev** [WP-API/node-wpapi#321]
I have a locally hosted wp install with the auth plugin installed and am using a node script to interface with the site (bulk manage tags, etc)

I can fetch all existing tags just fine which makes me think that my script is authenticating.

When I try to create a tag, I guess this error:

```
  { code: 'rest_cannot_create',
    message: 'Sorry, you are not allowed to create new terms.',
    data: { status: 401 } }
```

Here's my code:

    require('dotenv').config({path: '../.env'})
    var WPAPI = require( 'wpapi' );
    var wp = new WPAPI({
        endpoint: 'http://localhost:8000/wp-json',
        username: process.env.WP_USER,
        password: process.env.WP_PASS,
       auth: true
    });

    wp.tags().create({
        name: 'test'
    }).then(d => console.log(d)).catch(e => console.log(e))

I had it working once with what I believe was identical code to this, but now it's not working.

**Comment by motleydev** [comment]
Issue is related to process.env

**Comment by tinhochu** [comment]
@motleydev How do you Solved it?

**Comment by kadamwhite** [comment]
@tinhochu From the comment, I'd assume that the WP_PASS and WP_USER parameters weren't getting set properly on the environment object so the request was trying to authenticate with undefined credentials.

Other things to check, if you're getting a 401: Do you have the basic auth plugin installed & configured? Are you certain the credentials you're putting in are correct?

**Comment by tinhochu** [comment]
@kadamwhite yes, Not sure why when I made the docker-compose File, if the password as a `$` you need to scape it with double $$, but didn't work for me either. I paste the string as is for now. If you have any suggestion, let me know :)
