### ISSUE TITLE
Obtain raw content of posts without being authenticated

### ISSUE THREAD

**Issue by vuldin** [WP-API/node-wpapi#322]
I'm making a web application that calls the REST API to gather posts, users, etc. and then displays this information. Users of the site will be able to read posts without being logged in. The issue is that the REST API doesn't return the raw post content for unauthenticated GET requests.

This means that I must parse the rendered content, and in many cases remove styling, tags, CSS classes, and other attributes before having content that makes sense for me to render. My app is using React, so this type of parsing is important because I'm converting this text representation of elements into React components. For more info on this, I've been using [html-react-parser](https://github.com/remarkablemark/html-react-parser) to help with this task. But even with this parsing process in place, I still must deal with the tags and tag hierarchy that is given to me by the Wordpress editor.

This parsing step seems like the wrong long term approach. The best possibility seems to be to get the raw post content and use that as my starting point for generating whatever representation of that content I want in the webapp. But I can't rely on people being logged in, since the site is basically a news site where the vast majority of users will only visit to read content.

Is it possible to allow for raw content to be passed along in unauthenticated requests?

**Comment by kadamwhite** [comment]
It is possible, but you'd have to write some plugin code in the PHP side. Either you could use a filter to add in the raw content to the post, or make a custom endpoint to surface that data. This is an acknowledged weakness of the API that is an unavoidable side effect of the traditional web publishing orientation of WP's history. 

As a caveat, many sites that I've seen have proprietary information latent in their short codes that they may not want exposed. If this is something you'd be distributing to sites you don't control id suggest making it totally clear that raw post content will be publicly available.

**Comment by vuldin** [comment]
Creating a plugin that changes the filter so that raw content is returned seems like the best approach for my situation. Thanks for pointing me in this direction! I assume [this](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/) is the best source of information on this task.

**Comment by vuldin** [comment]
If anyone finds this later, [here is the plugin](https://github.com/vuldin/raw-post-mod) that does basically what is described above. The only issue now is the raw data is also not in a very usable format, but this is a different issue. I discuss what I'm hoping to do about this [here](https://github.com/vuldin/raw-post-mod#future-plans).
