### ISSUE TITLE
Clarify usage within React Native applications

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/node-wpapi#323]
#300 establishes that React Native does not bundle all the same dependencies that Node does; we should either depend on these shim libraries directly so that this project can be used independently of environment, or else clarify the React Native-specific requirements somewhere in the docs.

**Comment by vijayst** [comment]
I like to use this package with React native, if possible. As of now, I get a red screen when used with React native. Something to do with bundling.

**Comment by kadamwhite** [comment]
Neither `util` nor `url` are in use within this project any longer. No special installation note should be needed.
