### ISSUE TITLE
Fetching posts not authenticating properly.

### ISSUE THREAD

**Issue by motleydev** [WP-API/node-wpapi#325]
I commented on the issue [here](https://github.com/WP-API/node-wpapi/issues/154#issuecomment-312186212) and even posted the issue on [SO](https://stackoverflow.com/questions/44840350/fetching-drafts-forbidden-in-wordpress-rest-api) but now I'm opening a new issue to try and figure this out.

I've tried nearly every convocation of fetching drafts. My primary site constructor is using Basic Auth and works to fetch/create/delete posts. It even created the draft posts in questions.

When I go to fetch, I get this error:

```javascript
{ code: 'rest_invalid_param',
  message: 'Invalid parameter(s): status',
  data: { status: 400, params: { status: 'Status is forbidden.' } } }
```

I've used these various methods for trying to fetch drafts:

```javascript
wp.posts().auth().param( 'context', 'edit' ).param('status', 'draft')
wp.posts().auth({
  username: process.env.WP_USER,
  password: process.env.WP_PASSWORD
}).param('status','draft')
```

as well as various versions with `.status('draft')`, `.param({status: 'draft'})` as well as removing the `.auth()` method chaining, etc.

After some further attempts I was able to fetch the drafts by bypassing the library all-together and using request. Further, I was able to fetch the posts normally by swapping out `draft` with `publish` and that returns the public posts. This leads me to the assumptions:
1. My authentication is correct.
2. There's a bug somewhere in the library's auth mechanism.

Thanks for any help on this!

**Comment by kadamwhite** [comment]
Thanks for filing this issue, i'd seen the SO post but hadn't had time to dig into it. I'll see if I can replicate today and hope to get you a response by the end of the weekend.

**Comment by motleydev** [comment]
Sweet! And I wasn't trying to complain with the references, more provide a canonical reference! :)

**Comment by motleydev** [comment]
@kadamwhite I think I have some more context. I tried to basically recreate a recursion/pagination feature for fetching drafts using request. I discovered that, since the implicit auth doesn't seem to work when fetching drafts (I had to add it to the headers explicitly) the "next" link also doesn't have implicit auth. I had to add the auth into my request function (interestingly it caused an error with every request method except a hashed Authentication header) so that it requested authentication for each subsequent page until the pagination was done. Maybe this helps the debug process.

**Comment by kadamwhite** [comment]
@motleydev Are you sure the user you are authenticating with has the rights to view draft posts? With an admin-level user, this snippet works on every site I have running that uses Basic Auth:
```js
wp.posts().auth().param( 'context', 'edit' ).param( 'status', 'draft' )
	.then(results => console.log(results.map(p => p.title.rendered)))
	.catch(e => console.error(e));
```
I get the list of draft posts as expected

**Comment by kadamwhite** [comment]
@motleydev I was digging in to the wrong problem, I see why authentication isn't being maintained across requests and there is a PR and release incoming today to fix it :)

**Comment by motleydev** [comment]
Sweet! Great work!

**Comment by souljuse** [comment]
I am still having this issue. I am using version 1.2.1

```
const WPAPI = require('wpapi');
const wp = await WPAPI.discover("http://localhost:8081");
const wpSite = await wp.auth({ username: wpUser, password: wpPassword });
const foo = await wpSite
    .auth({ username: wpUser, password: wpPassword })
    .posts()
    .param('status', 'draft');
});
```

And I still get this `Error: Invalid parameter(s): status`. Am I doing something wrong?

**Comment by carli2** [comment]
I'm still having this issue with wordpress 6.8.2:

```bash
carli@launix-MS-7C51:~/projekte/n8n-launix$  curl -u carli:**** https://launix.de/launix/wp-json/wp/v2/posts?status=draft|jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: curl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   265    0   265    0     0    816      0 --:--:-- --:--:-- --:--:--   815
{
  "code": "rest_invalid_param",
  "message": "Ungültige(r) Parameter: status",
  "data": {
    "status": 400,
    "params": {
      "status": "Status ist unzulässig."
    },
    "details": {
      "status": {
        "code": "rest_forbidden_status",
        "message": "Status ist unzulässig.",
        "data": {
          "status": 401
        }
      }
    }
  }
}
```
