### ISSUE TITLE
Whats the new way of filtering posts by tags?

### ISSUE THREAD

**Issue by igoldny** [WP-API/node-wpapi#330]
Hey,
I'm trying to upgrade from wpapi 0.9 to latest.
previously I've been using filters for filtering posts by tags.

I have a use case where I need to query by tags and ".tags()" don't fully fit.

currently, tags return posts with "tag1" or "tag2"
and I need a way to filter as such:

include: "tag1" and "tag2" and ("tag3" or "tag4")
exclude: "tag5"

with the previous API that would look like this:

```
this.wordpress
.posts()
.filter({
    tag_slug__and,
    tag_slug__in,
    tag__not_in
})
```

whats the right way to do it now?

**Comment by kadamwhite** [comment]
The recommended way to filter by taxonomy term slugs is to fetch the terms separately, note their ID, and query with IDs as usual: `.tags( id1, id2 )`. This is recommended because tag IDs are a more stable indicator than slugs, and all relationships in the API are ID-driven.

The filter query parameter can be reinstated however by installing the plugin at github.com/WP-API/rest-filter; if you use auto-discovery on a site with that plugin enabled then the bound client will provide the old `.filter` method. 

Hope this helps! Closing the issue as it doesn't seem to represent a bug; frustrating though it may be, that's how the core API is designed to work. 

(Providing a way to do AND relations, however, is still on the roadmap and is being tracked in the core WP trac ticketing system)

**Comment by kadamwhite** [comment]
I missed the complexity of the query you want to make; for that usage yes, I think the rest-filter plugin will be required. However for "not in," you should be able to use the `tags_exclude` parameter

**Comment by igoldny** [comment]
thnx for the quick response.
I've tried your suggestion following the docs but came across an error.
seems like the filter function not implemented or am i doing something wrong?

```
WPAPI.discover( 'http://mysite.com' )
    .then(function(wp) {
        wp.posts().filter({
            category_name: 'islands',
            tag: [ 'clouds', 'sunset' ]
        })...
    });
```

this lines of code thorw an error:
"TypeError: wp.posts(...).filter is not a function"

**Comment by kadamwhite** [comment]
Just to check -- you do have the rest-filter plugin installed and active?

**Comment by igoldny** [comment]
yes, I did but even if it's not installed I think filter supposed to be available and the answer from the server will fail but it, not the case, I get js error that filter function not found.

**Comment by kadamwhite** [comment]
The filter method is only available if you use auto-discovery: https://github.com/WP-API/node-wpapi/blob/master/README.md#other-filters it's available as a mixin for use with custom endpoint handlers, but the out-of-the-box WP client methods this library provides are based around a current snapshot of the functionality of the core REST API, and unfortunately this does not include filter. I'd be open to making an easier method to add mixins to already-configured route handlers, but I'd want to understand why filter isn't available for you after auto-discovery, first. If you look at the output of `yoursite.com/wp-json`, do you see "filter" included in the list of parameters on the posts collection?

**Comment by igoldny** [comment]
are you sure filter available when you use auto-discovery? I get an error that filters function not available in auto-discovery and nothing is been sent...

**Comment by kadamwhite** [comment]
@igoldny it should be available, yes; please see my question above about whether you see it enumerated in the output from the root wp-json output. If it's there, then the fact filter does not work is a bug, if it's not there then the bug is in the rest-filter plugin.

**Comment by igoldny** [comment]
@kadamwhite yes looks like filter is there when i'm using "category_name" instead of category with id
i get this output:
```
fxapi [17/Jul/2017:12:49:20 +0000] "GET /wp-json/wp/v2/posts?_embed=true&filter%5Bcategory_name%5D=forecasts&page=1&per_page=6 HTTP/1.1" 200 58673 "-" "node-superagent/3.5.2"
```

but can't test that with auto-discovery coz it's not working here
same query with auto-discovery with not sent any request to wp and i will get error that filter function not working.

```
wpapi.discover('http://wp.fxempiredev.com')
            .then(function(wp) {
                return wp.posts().filter({
                    category_name: 'news'
                })
            });

TypeError: wp.posts(...).filter is not a function
```

**Comment by arikogan** [comment]
Hi @kadamwhite. My name is Ariel, I work with @igoldny.
He asked me to take a look at the WordPress instance. To your question, filter doesn't return as a possible parameter of the posts collection.
I'm a newbie when it comes to WordPress code, however I'm happy to try to set up a new instance in a different way. Did you by chance manage to get this plugin running? If so, with which version of WordPress?
Thanks in advance for the help.
