### ISSUE TITLE
Simplify auto-discovery process

### ISSUE THREAD

**Issue by kadamwhite** [WP-API/node-wpapi#334]
@rmccue notes that appending `?rest_route=/` to a WordPress URL will yield the root response JSON (e.g. [make.wordpress.org/core/?rest_route=/](https://make.wordpress.org/core/?rest_route=/))—this is simpler than trusting to the presence of a header or an HTML `<link>` element, and we can use the `self` relation for the root API route to determine that base URL.

**Comment by rmccue** [comment]
[Here's how I'm doing discovery](https://github.com/rmccue/wordpress-rest-api-oauth-2/blob/411baeb52344462f17bcd0d872480147b64be700/src/index.js#L296-L318) FWIW.
