### ISSUE TITLE
Unable to create posts. 

### ISSUE THREAD

**Issue by pauldariye** [WP-API/node-wpapi#335]
Here's my code:

Auth:

```
const wp = initializeWP()

function initializeWP() {
  return WPAPI.discover(wpEndpoint)
    .then((site) => (site.auth(wpUser)))
}

```

`create`
```
  wp
    .then((site) => { 
      site.posts().create({
        title: 'Why you no work?',
        content: 'Please work, work, work, work, work',
        status: 'publish'
      }).then((response) => {
        console.log('Response: ' + response.id)
      }).catch((error) => {
        console.log('Error writing to wordpress: ' + error)   
      })
    })
```

The response returns undefined. I'm able to `get()` posts just fine with no issues. I'm using wordpress `4.8.1`

**Comment by dambrogia** [comment]
I'm also unable to auth using version `4.8.1`. 

I have installed the `basic-auth.php` file from the this repo: 
https://github.com/WP-API/Basic-Auth

OP might want to check that they've completed this step.

I can provide the code I have if needed, but it seems like it's the same situation as the OP.

**Comment by dambrogia** [comment]
Based on feedback provided within [this thread](https://github.com/WP-API/Basic-Auth/issues/35) it looks like this problem isn't related to this repository specifically, but has to do with your server configuration and the WP REST API.

There are multiple suggestion in the previously mentioned thread to get you started in the right direction.

**Comment by pauldariye** [comment]
@dambrogia I'll give the `.htaccess` solution a try.

**Comment by dambrogia** [comment]
I ran into a problem with PHP-CGI changing the name of my headers, once I was able to fix that I had to test the connection in an incognito browser. It would work _only_ in an incognito browser. I'm assuming this is because I was logged in as a different user within the wp-admin. 

Personally, I didn't have to make any changes to an `.htaccess` file

**Comment by kadamwhite** [comment]
It sounds from the discussion above that this was related to server configuration and not library behavior. If this is inaccurate, please leave a comment or open a new issue to keep the conversation going.

Thank you @dambrogia for chiming in to provide support here!
