### ISSUE TITLE
Possible alternative to using superagent (NSP Security Issue)

### ISSUE THREAD

**Issue by alexlapinski** [WP-API/node-wpapi#337]
We currently make use of the npm package "wpapi" and we also make use of Node Security Platform (nsp) to run security checks on packages.

It looks like an issue has cropped up with the dependency of wpapi "superagent". I was wondering if there are any plans to move to a different http request library, or if you will just be waiting for the security issue to be addressed within superagent itself.

https://nodesecurity.io/advisories/479

**Comment by kadamwhite** [comment]
@alexlapinski Thanks for raising the issue! We hadn't had any intent to move away from superagent, but I will try to contact their team to understand the issue and if it doesn't look like it is going to be addressed quickly we will either consider a switch, or I can better document how you can implement your own transport to utilize an alternative library

**Comment by kadamwhite** [comment]
This is addressed in the `alpha` tag (`2.0.0-alpha.1` at this time). We have upgraded Superagent, and furthermore the v2 of this library will support a wider range of transport options and superagent specifically will be an `optionalDependency`.
