### ISSUE TITLE
Remote image upload

### ISSUE THREAD

**Issue by reinierkors** [WP-API/node-wpapi#340]
Hi, is it possible to upload a remote image from an url?

I've tried the following:
```javascript
const url = 'https://i.imgur.com/e5mRFg5.png';
const requestSettings = {
    url,
    encoding: null
};
rp(requestSettings).then((res) => wp.media().file(res)
    .create({
        title: 'My awesome image',
        alt_text: 'an image of something awesome',
        caption: 'This is the caption text',
        description: 'More explanatory information'
    }))
    .then(response => console.log("Uploaded with id: ",response.id))
    .catch(err => console.log(err));
```

I keep getting the following error:
```javascript
{ code: 'rest_upload_no_data',
  message: 'No data supplied.',
  data: { status: 400 } }
```

Thanks!

**Comment by kadamwhite** [comment]
Thanks for your question! Loading remote images is not currently supported by the WordPress REST API,  so it is not something this library supports either. The best suggestion I could offer would be to use node to download the file and then upload it to WordPress; I don't have a comparable solution for use on the client side however. 

Best of luck!
