### ISSUE TITLE
wp.media().onprogress()

### ISSUE THREAD

**Issue by Peh4** [WP-API/node-wpapi#341]
Hello
is there a way to catch the uploading progress of an image ? 
something like 
wp.media()
  .file(image)
  .create({…})
  **.onprogress(function (e) {
      console.log(e)
  })**
  .then(…)

**Comment by kadamwhite** [comment]
This is a little overly specific to implement within the library (we do not know where the code is deployed, so it would be presumptuous to implement a node-specific loading bar when many users will be browser-side, we don't have a generic way to integrate with other loading logic, etc); however, we're looking at adding a more generic way to modify the SuperAgent request object before sending the request, in which case `superagent-progress` or some other plugin could be used to accomplish this. I'm going to close this issue out in favor of the more generic #324.
