### ISSUE TITLE
rest_upload_no_data issue

### ISSUE THREAD

**Issue by cungminh2710** [WP-API/node-wpapi#344]
I had a piece of NodeJs code that retrieve buffer from a image URL then upload to Wordpress using wp.media().
```javascript
const axios = require('axios');
// Setting up wordpress library and auth 
const wordpress = require('wpapi');
const wp = new wordpress(auth);

let retrieveImageBuffer = url => axios
		.get(url, {
			responseType: "arraybuffer"
		})
		.then(response => Promise.resolve(new Buffer(response.data, "binary")));
}

let run = async (url, fileOption) => {
                let buffer = await retrieveImageBuffer(url);
		try {
			let result = await wp
				.media()
				.file(buffer)
				.create(fileOption);
		} catch (err) {
			console.log(err.message);
		}
}

run(url, fileOption);
```

What I get after running the script: `Error: No data supplied`

**Comment by mvhirsch** [comment]
I have the same problem. Anyone can help with a working example on how to use `Buffer`?

**Comment by mvhirsch** [comment]
@cungminh2710 I just ran into the same issue. I was able to solve it by applying a filename as second parameter: `wp.media().file(buffer, 'image.jpg').create(fileOption)`.

Hope this helps.

Greets, Michael

**Comment by subatomicceo** [comment]
Getting the same issue here even with adding the filename as a second param. I'm grabbing the File object from a standard HTML input on the frontend. Any help will be greatly appreciated!

`
// Client Code
function getBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => resolve(reader.result.replace(/^data:image\/\w+;base64,/, ''));
    reader.onerror = error => reject(error);
  });
}

function uploadCallback(file) {
  getBase64(file).then(data => {
    uploadFile( file, data)
  })
}

// Server Code
function uploadFile(file,data){
    wp.media()
            .file(Buffer.from(data, 'base64'), file.name)
            .create({
                title: 'My awesome image',
                alt_text: 'an image of something awesome',
                caption: 'This is the caption text',
                description: 'More explanatory information'
            })
            .then(( response ) => {
                console.log('response ==>', response)
                return response
            })
            .catch(( err ) => {
                console.log('err ==>', err)
                throw new Meteor.Error('wp-media', err);
            });
}
`

Error: { code: 'rest_upload_no_data', message: 'No data supplied.', data: { status: 400 } }

**Comment by kadamwhite** [comment]
Thank you @cungminh2710 for raising the issue, and @mvhirsch for identifying the problem. We will be shipping an improved error notification for this situation in the upcoming v1.2.2 release so that it is more obvious that `name` is required when passing `.file()` a `Buffer` object. We have also expanded the documentation with a note about the issue.

I appreciate your support!
