### ISSUE TITLE
REST API gives old data

### ISSUE THREAD

**Issue by chittasec** [WP-API/node-wpapi#348]
Hello,

I use WordPress 4.9.1 running Ribosome theme.
I use node-wpapi in node.js to get post data for another downstream system .
I updated one post title . But REST API returns the old title .
Then I tried to get the response in a loop and surprised to see that sometimes the old and sometimes the new title in returned from the REST API .

Can somebody advise how do I avoid this and awlays get the current post-data .

Thanks,
Chitta

**Comment by kadamwhite** [comment]
This sounds like it's a WordPress REST API support question, not something specific to this client library; I'd encourage you to try posting to the WordPress forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ with the topic tag "rest-api" for support. I suspect there's some sort of caching in your system that is causing the API to return stale data.

However, if you find you're able to consistently reproduce the issue and there's no caching in your environment, then that might be a good thing to bring up on the WordPress core issue tracker: https://core.trac.wordpress.org

Thanks!

**Comment by kadamwhite** [comment]
Actually, reading your "in a loop," I think I may have a better idea of what's going on. If you make these two calls:

```js
wp.posts().create( {
  title: 'Test Title',
  content: 'Test Content',
});
wp.posts().get().then( posts => console.log( posts ) );
```
then the log statement is almost certainly not going to contain your new post, because WordPress receives the requests simultaneously and the new post won't have had time to be created before WordPress returns the list of existing posts. To see the updated date of a post, you'd need to wait for your Promise to resolve:
```js
wp.posts().create( {
  title: 'Test Title',
  content: 'Test Content',
} )
.then( () => wp.posts().get() )
.then( posts => console.log( posts ) );
```
Hope this helps, @chittasec

**Comment by chittasec** [comment]
Thank you kadamwhite . Appreciate your long reply. I found out that when I disable caching with the hosting provider , I was getting correct data . hence I concluded it is a caching issue and disabled the caching .

**Comment by kadamwhite** [comment]
@chittasec I'm glad to hear that the response helped! Caching is useful for the front-end of a site but can (as you discovered) be a challenge for API responses, so if your provider allows you to do so, disabling caching just within the `wp-json/` routes is ideal.
