### ISSUE TITLE
401 : Sorry, you are not allowed to create posts as this user

### ISSUE THREAD

**Issue by jangirsuresh95** [WP-API/node-wpapi#349]
I have tried the same thing mentioned in it and I am getting below error message.

the account I am using is the Administrator and I have WP BASIC Auth (https://github.com/wokamoto/wp-basic-auth) plugin installed. 

```
{
    "data": {
        "code": "rest_cannot_create",
        "message": "Sorry, you are not allowed to create posts as this user.",
        "data": {
            "status": 401
        }
    },
    "headers": {
        "Allow": "GET"
    },
    "status": 401
}
```

**Comment by jangirsuresh95** [comment]
I am able to solve this problem. it was some misconfiguration in .htaccess file. I have installed "Application Passwords" plugin which indicated the problem in htaccess file.

**Comment by richplastow** [comment]
For anyone else who encounters this problem, you don’t need to install the ‘Application Password’ plugin — just follow the instructions given here:
https://github.com/georgestephanis/application-passwords/wiki/Basic-Authorization-Header----Missing

**Comment by samdoj** [comment]
No amount of hacking the .htaccess file nor installing this plugin has the correct effect.  Whenever I try to upload media with credentials that I know to be correct, I get "Sorry, you are not allowed to create posts as this user".  This makes absolutely no sense as the user is me and I'm an admin.

**Comment by Manish-Muttreja-Bose** [comment]
I am getting the same problem, followed all the steps and its still failing to upload media with credentials that are correct.  The error is same as @samdoj and it happens even with admin users.

**Comment by amet-93** [comment]
{
    "code": "rest_cannot_create",
    "message": "Sorry, you are not allowed to create posts as this user.",
    "data": {
        "status": 401
    }
}

i am unable to solve this issue please help

**Comment by amet-93** [comment]
> I am getting the same problem, followed all the steps and its still failing to upload media with credentials that are correct. The error is same as @samdoj and it happens even with admin users.

did you solve this ?

**Comment by mattcullenmeyer** [comment]
I spent hours facing the same problem and finally got it to work. The only plugin I installed was Application Passwords. I also edited the .htaccess file per the comments above. The issue I ran into was what username to use for the authorization header. I was trying to use the name assigned to the password generated through Application Passwords. In reality, you should use your actual username, which in my case is just "admin" (along with the password from Application Passwords).

**Comment by gotofritz** [comment]
I have the same issue and I cannot solve it with the free plan on wordpress.com as I cannot install plugins

This is a bug, it should just work and I shouldn't need to install plugins. Thanks

**Comment by smartm0use** [comment]
> For anyone else who encounters this problem, you need to install and activate the ‘Application Passwords’ plugin and then follow the instructions given here:
> https://github.com/georgestephanis/application-passwords/wiki/Basic-Authorization-Header----Missing
> But you don’t need to actually set up any Application Passwords for your users.

This does the trick! Thank you.

**Comment by arunbasillal** [comment]
The original suggestion didn't work for me (On Local by Flywheel)
This worked: https://wordpress.stackexchange.com/a/310898/90061

**Comment by geniecoder** [comment]
I was facing the same issue and the problem is, I forgot to add these lines in **htaccess** file.

`RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule ^(.*) - [E=HTTP_AUTHORIZATION:%1]
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

You can also check below link to know how and where to add these lines.

[https://github.com/imranhsayed/react-with-wordpress/](url)

**Comment by iDanielBH** [comment]
I had a similar problem, and my problem was that it used the "Application Passwords Name" as the username. And the normal username has to be used.

He also doubted whether to use the password with spaces or without spaces, finally it was with spaces.

**Comment by LukeV111** [comment]
> I spent hours facing the same problem and finally got it to work. The only plugin I installed was Application Passwords. I also edited the .htaccess file per the comments above. The issue I ran into was what username to use for the authorization header. I was trying to use the name assigned to the password generated through Application Passwords. In reality, you should use your actual username, which in my case is just "admin" (along with the password from Application Passwords).

This is the actual answer here.

Same username, but generated Application Password.

**Comment by kirankumarbiradar** [comment]
**go to  .htaccess file and replace all below text**


\# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteRule .* - [E=REMOTE_USER:%{HTTP:Authorization}]
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

\# END WordPress

**Comment by BabcoxDeveloper** [comment]
For folks that are still having issues even though their rules in .htaccess are correct: Does the username you are using have a space in it (eg: firstName lastName)? If so, create a new user with a username without a space (eg: firstNameLastName). This fixed the issue for me. Remotely connecting from another WordPress site was working fine for me but connecting from Power Automate was NOT until I used a username without a space. Hope this helps!

**Comment by sagar03d** [comment]
<img width="1271" alt="Screenshot 2024-04-13 at 10 17 07 AM" src="https://github.com/WP-API/node-wpapi/assets/19644555/0b659c06-525c-472b-8b86-8d5d7af20a81">
I resolved this by creating an Application Password From 'User' Menu

**Comment by adjieguntoro-tokped** [comment]
> <img alt="Screenshot 2024-04-13 at 10 17 07 AM" width="1271" src="https://private-user-images.githubusercontent.com/19644555/322177939-0b659c06-525c-472b-8b86-8d5d7af20a81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMTQxMDgsIm5iZiI6MTcxODIxMzgwOCwicGF0aCI6Ii8xOTY0NDU1NS8zMjIxNzc5MzktMGI2NTljMDYtNTI1Yy00NzJiLThiODYtOGQ1ZDdhZjIwYTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE3MzY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4YmIzZmNkZGNjODRhYWZlMWFiM2Y1NWI0ZDhlODk1ZjA0ZDEzYWU0ODAzZTY2NGE2ZTJjZDc3MTk1ZDhjNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jC-S8k358DdTZqJwJqQru6KU1UK6mgv9aGuzW0p6NPE"> I resolved this by creating an Application Password From 'User' Menu

Thank you...

**Comment by rimi-web** [comment]
The problem stemmed from a permissions issue with the WP BASIC Auth plugin, despite using an Administrator account. After adjusting the necessary settings, the error [Sorry, you are not allowed to upload this file type](https://devrims.com/blog/sorry-this-file-type-is-not-permitted-error-in-wordpress/) no longer occurs.

**Comment by shiyouben88** [comment]
> I spent hours facing the same problem and finally got it to work. The only plugin I installed was Application Passwords. I also edited the .htaccess file per the comments above. The issue I ran into was what username to use for the authorization header. I was trying to use the name assigned to the password generated through Application Passwords. In reality, you should use your actual username, which in my case is just "admin" (along with the password from Application Passwords).



> I spent hours facing the same problem and finally got it to work. The only plugin I installed was Application Passwords. I also edited the .htaccess file per the comments above. The issue I ran into was what username to use for the authorization header. I was trying to use the name assigned to the password generated through Application Passwords. In reality, you should use your actual username, which in my case is just "admin" (along with the password from Application Passwords).

We should push this to Top solution!!!

**Comment by ahmednabik** [comment]
You should use Application password instead of your regular user password. For each user, you can create Application password on the user edit page.

**Comment by exceptionSPG** [comment]
> I spent hours facing the same problem and finally got it to work. The only plugin I installed was Application Passwords. I also edited the .htaccess file per the comments above. The issue I ran into was what username to use for the authorization header. I was trying to use the name assigned to the password generated through Application Passwords. In reality, you should use your actual username, which in my case is just "admin" (along with the password from Application Passwords).

This worked for me. Use your actual username instead of application password name.

**Comment by tobinbc** [comment]
I spent waaaay too long on this so I made a PR to update the docs: https://github.com/WP-API/docs/pull/207

**Comment by mpint** [comment]
Others have aluded to it but the username is `some-user`, not `some-user@yoursite.com`
