### ISSUE TITLE
No error or information provided when auth not setup properly

### ISSUE THREAD

**Issue by hgezim** [WP-API/node-wpapi#353]
I got reading the docs, attempted a post creation as follows:

const WPAPI = require('wpapi');

var wp = new WPAPI({
    endpoint: 'https://www.example.net/wp-json',
    // This assumes you are using basic auth, as described further below
    username: 'hgezim',
    password: 'pass',
    auth: true
});

wp.pages().create({
    // "title" and "content" are the only required properties
    title: 'Your Post Title',
}).then(function( response ) {
    // "response" will hold all properties of your newly-created post,
    // including the unique `id` the post was assigned on creation
    console.log("sup....");
    console.log('supt:', response);
    console.log("all: ", arguments);
    console.log( response.id );
});

I got no error or any other information saying auth failed. I didn't install https://github.com/WP-API/Basic-Auth as I missed that part in docs.

This also happens if I have wrong password after installing Basic Auth plugin on my site.

**Comment by kadamwhite** [comment]
Your example code here does not include any Promise error handling -- if you add a
```js
.catch( function( error ) {
    console.log( error );
} );
```
to the end of the promise chain, you should see an authentication error. I'm going to close this as it appears not to be an issue with the library itself (Promise error handling can be confusing, but it's what we have to work with); if you find that doing as I suggested does not work, please comment below and we can re-open to investigate. Thanks for trying out the library!
