### ISSUE TITLE
Inconsistent with wp-cli

### ISSUE THREAD

**Issue by hgezim** [WP-API/node-wpapi#354]
In wp-cli to create an instance of a custom post type, I run this:

`wp post create --post_type=epkb_post_type_1 --post_title='A sample post from wp-cli'`

In JS the same doesn't work:

```
wp.posts().create({
    // "title" and "content" are the only required properties 
    type: 'epkb_post_type_1',
    title: 'Installing'
}).then(function( response ) {
    // "response" will hold all properties of your newly-created post, 
    // including the unique `id` the post was assigned on creation 
    console.log("sup....");
    console.log('supt:', response);
    console.log("all: ", arguments);
    console.log( response.id );
});
```

A regular post is created instead of my custom post type. Why are these not consistent? `wp-cli` seems much easier to use.

Why am I not just using it? I can't get it to work with remote WP install.

**Comment by kadamwhite** [comment]
The REST API separates types out by endpoint, so you would create an `epkb_post_type_1` item at `/wp-json/wp/v2/epkb_post_type_1`, not `wp-json/wp/v2/posts`. While this is a point of contention, it's a property of the design of the REST API (which WP-CLI uses, but which at core is a separate system from the CLI tool), and not something we can change in this library. We evaluated using a `type` argument on outgoing requests to change what resource was created, but it introduced more confusion than it solved in the app we used to prototype this library, so now the recommended approach for custom post types is to use [autodiscovery-bound handlers](http://wp-api.org/node-wpapi/using-the-client/#auto-discovery) or [`registerRoute`](http://wp-api.org/node-wpapi/custom-routes/).

I recognize this doesn't answer your question, but I hope it helps explain the situation. If you can use WP-CLI, I think you will find that an easier tool when dealing with command line usage. This library was designed for Node and browser applications where WP-CLI would not be available. Thanks for trying out this library!
