### ISSUE TITLE
Return error information instead of logging to console

### ISSUE THREAD

**Issue by qgustavor** [WP-API/node-wpapi#355]
`node-wpapi` use promises but [wpapi.js](https://github.com/WP-API/node-wpapi/blob/7427d6fbee11cc0f20d5b977c75ff927a2c49dbf/wpapi.js#L453) uses the console to pass error details.

*Expected Behavior:* errors are passed to the catch function, where those can be handled.

*Current Behavior*: the error is passed to the catch function *and* logged to the console.

*Possible Solution*: remove the `console.error` and `console.warn` lines; handle those warnings in a way which allows those to be handled by the code which is using this client, not by the user.

*How to reproduce:* ([RunKit link](https://runkit.com/embed/emijlvwzukno))

```javascript
WPAPI.discover('http://example.com').catch(error => {
  // The error is logged twice
  console.error(error)
})
```

**Comment by kadamwhite** [comment]
You make an excellent point, thanks for raising the issue. I don't have a lot of bandwidth to work on this project until next month, so if you have any energy to put together a PR I'd be grateful; otherwise, we'll prioritize this once I have the bandwidth!

**Comment by qgustavor** [comment]
I edited the wpapi.js in node_modules as a temporary fix replacing [those lines](https://github.com/WP-API/node-wpapi/blob/7427d6fbee11cc0f20d5b977c75ff927a2c49dbf/wpapi.js#L453-L459) with those ones:

```javascript
if ( endpoint ) {
	const site = new WPAPI.site( endpoint );
	site.usingDefaultRoutes = true;
	return site;
}
throw new Error( 'Autodiscovery failed' );
```
 I removed the `console.log` lines and instead of using `console.warn` a `usingDefaultRoutes` property to is the site object when the default routes are assumed. I don't know if it's a acceptable solution for a pull request, probably not.
