### ISSUE TITLE
Using Custom Field Suite

### ISSUE THREAD

**Issue by andricicezar** [WP-API/node-wpapi#357]
I am trying to use wpapi with [Custom Field Suite](https://github.com/mgibbs189/custom-field-suite) and I don't find any solution to make it work. The problem is that no Custom Field is set/updated when I create/update a post. I don't think that it is a problem with wpapi, but I don't find any solutions and I really need help. I opened the ticket first [here](https://github.com/mgibbs189/custom-field-suite/issues/423).

Is there any other way of creating CPT with Custom Fields without writing code and after that inserting new posts (with the custom fields) with wpapi?

Thank you in advance!

**Comment by kinizumi** [comment]
did you read this?
https://support.advancedcustomfields.com/forums/topic/json-rest-api-and-acf/

**Comment by andricicezar** [comment]
Don't think so. Anyway, I fixed it in a way or another.
