### ISSUE TITLE
Unable to make create postwith attached media

### ISSUE THREAD

**Issue by Dignity1988** [WP-API/node-wpapi#360]
Hello i have followed documentation in creating 2 different calls. One to create posts. And second upload and attach media files like here:
https://github.com/WP-API/node-wpapi#uploading-media.
Can anyone suggest me thesample of code to upload media and attach it.
I have used uploading loop to get files uploaded from folder and here is my code:
```

var fs = require( 'fs' );
var path = require( 'path' );
// In newer Node.js versions where process is already global this isn't necessary.
var process = require( "process" );
// Loop through all the files in the temp directory
fs.readdir( moveFrom, function( err, files ) {
  var moveFrom = "/home/directory/";
        if( err ) {
            console.error( "Could not list the directory.", err );
            process.exit( 1 );
        }

        files.forEach( function( file, index ) {
                // Make one pass and make the file complete
                var fromPath = path.join( moveFrom, file );
              //  var toPath = path.join( moveTo, file );
//starting getting filenames
                fs.stat( fromPath, function( error, stat ) {
                    if( error ) {
                        console.error( "Error stating file.", error );
                        return;
                    }

                    if( stat.isFile() ){
                      var WPAPI = require("wpapi");
                       var site = new WPAPI({
                      endpoint: 'http://site/wp-json/',
                      username: 'Maksym',
                      password: 'YfCDaWIC^ZQ$#NX3RAAeL6Lt'
                        });
                      console.log( "'%s' is a file.",moveFrom+file );
                      var fullpath=moveFrom+file; //specifying the fullpath to the images on node server or in file system.
                          site.posts().create({
                            title: 'This post has media, tags & categories!',
                            content: 'Excellent and compelling demonstration',
                          }).then(function( post ) {
                       site.media().file( filePath ).create({
                              title: 'Amazing featured image',
                              post:  post.id
                            }).then(function( media ) {
//updating media
                              // Set the new media record as the post's featured media
                            site.posts().id( post.id ).update({
                                featured_media: media.id
                              });
                           
                          });
                      });
}
                } );
        } );
} );

```

**Comment by mvhirsch** [comment]
Hi @Dignity1988 ,

just came around your issue. I think you're doing it correctly, but one small mistake:
You're defining ``var fullpath = moveFrom + file`` but using ``filePath`` (never defined) to create your media. Maybe that's your problem?

Cheers, Michael

**Comment by Dignity1988** [comment]
hi @mvhirsch ,
Thanks you writing back.

Its almost done for  now. But i am glad someone replied.
The final solution was like 
`  var WPAPI = require("wpapi");
    var site = new WPAPI({
      endpoint: 'http://new.whiteraven.org.ua/wp-json/wp/v2/trip',
      username: 'Maksym',
      password: 'YfCDaWIC^ZQ$#NX3RAAeL6Lt'
    });
var a,b,c;/*three levels of depth*/




//var moveTo = "/home/maksym/desktop/.raven/gallery/"

 
var
var moveFrom = __dirname+"/gallery/slider/";
var fs = require( 'fs' );
var path = require( 'path' );
// In newer Node.js versions where process is already global this isn't necessary.
var process = require( "process" );
// Loop through all the files in the temp directory
fs.readdir( moveFrom, function( err, files ) {

var moveFrom = __dirname+"/gallery/slider/";//setting up directory for file upload
        if( err ) {
            console.error( "Could not list the directory.", err );
            process.exit( 1 );
        }

        files.forEach( function( file, index ) {
                // Make one pass and make the file complete
                var fromPath = path.join( moveFrom, file );
              //  var toPath = path.join( moveTo, file );
//starting getting filenames
                fs.stat( fromPath, function( error, stat ) {
                    if( error ) {
                        console.error( "Error stating file.", error );
                        return;
                    }

                    if( stat.isFile() ){

                      var WPAPI = require("wpapi");
                       var site = new WPAPI({
                      endpoint: 'http://new.whiteraven.org.ua/wp-json/',
                      username: 'name',
                      password: 'pas'
                        });
                      console.log( "'%s' is a file.",moveFrom+file );
                      var fullpath=moveFrom+file;
                      var filename=file.replace('.jpg', '');//specifying the fullpath to the images on node server or in file system.
                      var WPAPI = require("wpapi");
                      var wp= new WPAPI({
                        endpoint: 'http://sitename/wp-json/',
                        username: 'name',
                        password: 'sitepas'
                      });
                      wp.posts().create({
                        title: filename,
                        content: filename,
                        category: '_categoryandfoldername__'
                      }).then(function( post ) {
                        // Create the media record & upload your image file
                        var filePath = fullpath;
                        return wp.media().file( filePath ).create({
                          title: 'Amazing featured image',
                          post: post.id
                        }).then(function( media ) {

                          // Set the new media record as the post's featured media
                          return wp.posts().id( post.id ).update({
                            featured_media: media.id
                          });

                        });
                      });
}








                } );
        } );
} );
`

but since i would like to parse the texts too. I have added [https://www.npmjs.com/package/article-parser].
`var parse = require('article-parser');


let url = 'http://page.com/page.php?30';

parse.extract(url).then((article) => {

text=new Array([article['content']],[article['title']]);console.log(text);





var i=1;
fs.writeFile(text[i]+'message.txt',text[0]+'Hello Node', function (err) {
  if (err) throw err;
  console.log('It\'s saved!');
});






}).catch((err) => {
  console.log(err);
});
`

I am going to loop through sitemap parse it and save locally.

Regards, Maksym

**Comment by Dignity1988** [comment]
Thanks . Stopped with script above. Project is done though.

**Comment by kadamwhite** [comment]
Closing as this seems resolved? Thank you @mvhirsch for chiming in!
