### ISSUE TITLE
uploading media from external url

### ISSUE THREAD

**Issue by ninjajs** [WP-API/node-wpapi#362]
Hi, I'm using the node-wpapi on the client side and I am wondering if there is an easy way to upload images from an external url.

For example if I have an image url: http://github.com/image.jpg

And I want to upload it to my wordpress site at http://examplewordpress.com

Is this currently possible?

**Comment by kadamwhite** [comment]
It sounds like you're asking about side-loading, effectively -- you have an application running on top of WordPress at http://examplewordpress.com and you wish to save the remote image http://github.com/image.jpg to your WordPress database. Is this correct?

Unfortunately, to my knowledge this is not currently supported by the API. The best I could recommend would be to create a custom endpoint to which you can post an object containing the URL of the image to download and the post to attach it to, then on the PHP side use [`media_sideload_image`](https://developer.wordpress.org/reference/functions/media_sideload_image/) to perform the side-loading.

I'm going to close this, as the capabilities of the WordPress REST API itself are beyond the scope of this client library's repository. But I hope the above helps! If you're interested, you could open a ticket at https://core.trac.wordpress.org to suggest an enhancement to support side-loading.
