### ISSUE TITLE
Offset

### ISSUE THREAD

**Issue by jonesmorgan** [WP-API/node-wpapi#367]
Have a load more, after a standard loop, which is pulling all of the posts.

Therefore trying to add in an offset, but appears to be doing nothing, tried this so far

``
import wp from "./api";

export default () => {
  $(".get-posts").on("click", () => {
    wp
      .posts()
      .get()
      .offset(3)
      .then(posts => {
        for (let post_index in posts) {
          let single_post = posts[post_index];
``

Any pointers would be great, thanks!

**Comment by kadamwhite** [comment]
All chaining methods need to be called before `.get()`, which is a chain terminator — so try flipping those two and it ought to work!

**Comment by jonesmorgan** [comment]
Hey Adam, that was it.

Tried that and working.

Thanks a lot for the help, much appreciated, have a great day!
