### ISSUE TITLE
Get post featured image and dimensions, in one API call.

### ISSUE THREAD

**Issue by jonesmorgan** [WP-API/node-wpapi#370]
Hi, just another question.

How do I (using `wp.posts().get()`) pull in a post's featured image, and its width + height, using a single API call?

(Or if this isn't possible using one call, how would I best do this generally?)

**Comment by kadamwhite** [comment]
You’re going to want to `.embed()` before you call get(), to include the image in the post response body. If the documentation isn’t clear please open an issue for what’s missing, either here or on github.com/wp-api/docs if it’s a question about the WordPress API itself.
