### ISSUE TITLE
problem in update

### ISSUE THREAD

**Issue by mohadesh** [WP-API/node-wpapi#371]
hi
i have a problem with update.
i cant update post or user whith libraries code. but create or get is work very well
my error is: Unsuccessful HTTP response

**Comment by kadamwhite** [comment]
@mohadesh Sorry to hear you're having difficulty. To be able to assist I'll need more details -- can you share examples of the request chains you're using that work, and those that do not?

**Comment by kadamwhite** [comment]
Closing due to lack of information
