### ISSUE TITLE
Filtering custom post type by ACF 

### ISSUE THREAD

**Issue by Randyjp** [WP-API/node-wpapi#372]
I have a CPT called "location" that has an ACF called "company_id", having a one company ID I would like to get all locations that match. I have been trying to create my own routes but I haven't been able to.

Location looks like this:
![screen shot 2018-05-28 at 5 33 56 pm](https://user-images.githubusercontent.com/4868558/40630060-5860e892-629d-11e8-8780-a2cbc19b55e8.png)

and my route looks like this: 

`   this.wp.locations = this.wp.registerRoute(
      this.namespace,
      "/location/(?P<id>\\d+)",
      {
        params: ["company_id"]
      }
    );
`

any hints what I'm doing wrong? Maybe I should be using mixins?

**Comment by kadamwhite** [comment]
Hey, @Randyjp ! To make sure I understand the question: Does the route work correctly in the browser? That is, when you query `/yournamespace/location/someid?company_id=blah` in the browser, you get the data you expect? I'm not sure from your issue whether the question is about whether this is the right way to register a handler to query that route with this library, or if you're wondering about the functionality of the underlying API endpoint.

**Comment by kadamwhite** [comment]
@Randyjp Thanks for the explanation! Unfortunately I think the question you're asking technically falls outside the scope of this library, which is intended to generate the queries, not to make them work on the WordPress side—for that reason, I am going to close this out as unrelated to `node-wpapi` specifically.

However, some food for thought that may help you proceed further:

I presume you're using [acf-to-rest-api](https://github.com/airesvsg/acf-to-rest-api) or similar to expose the ACF data in the REST response. I don't use ACF personally so I'm not familiar with the scope of these plugins' functionality, but it's possible that one of them may have a hook or syntax you can use to tell the endpoint to listen for that filter query parameter and limit accordingly.

Barring that, you could hook in to the filters within the REST API endpoint classes to check for that query parameter and inject the WP_Query arguments to filter on that company ID meta field. I think the filter you want is `rest_{$this->post_type}_query`, so `'rest_location_query` in this case assuming "location" is the name of your post type.

Sorry I cannot be of more assistance, but good luck! It's little help to you now, of course, but should you get this working we could use more documentation on filtering responses for https://github.com/wp-api/docs -- I'd welcome any additions to the documentation that you'd be interested in contributing. And, of course no obligation :)
