### ISSUE TITLE
Custom namespace results in "rest_no_route"

### ISSUE THREAD

**Issue by khadlock** [WP-API/node-wpapi#373]
Howdy,

We've created a custom namespace and routes under that namespace per the namespace suggestions on [WordPress.org](https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/#namespacing).

Example:
```
$namespace = 'summus/v1';
register_rest_route( $namespace, '/table', array(
	array(
		'methods' => 'GET',
		'callback' => array( $this, 'get_tables' ),
		'args' => array(),
	),
	array(
		'methods' => 'POST',
		'callback' => array( $this, 'create_tables' ),
		'args' => array(),
	),
) );
```

It works fine from Postman, etc. However, we are receiving a "rest_no_route" error when attempting to access it via node-wpapi.

Example:
```
var WPAPI = require('wpapi');
var wp = new WPAPI({
    endpoint: site_url + '/wp-json',
    username: username,
    password: password,
    auth: true
});
wp.customResource = wp.registerRoute('summus/v1/', 'table/(?P<id>\\d+)');
wp.customResource().create( {"data": "here"} ).then(function(res) {
    console.log('Success: ', res.id);
}).catch(function(err) {
    console.log('Error: ', err);
});
```

**Comment by kadamwhite** [comment]
What do you get if you say `console.log( wp.customResource().toString()`? Off the top of my head I'm wondering if you need to omit the trailing slash in the namespace property in the `wp.registerRoute` call.

**Comment by khadlock** [comment]
Thank you @kadamwhite. The issue was the trailing slash, we changed the `registerRoute` to the following:

`wp.customResource = wp.registerRoute('summus/v1', 'table/(?P<id>\\d+)');`
