### ISSUE TITLE
Upload media from remote resource

### ISSUE THREAD

**Issue by robertmylne** [WP-API/node-wpapi#376]
How can I use an absolute uri to specify the medias file path and not a relative one to the specific folder.

**Comment by kadamwhite** [comment]
This is not currently possible through the underlying WordPress REST API, so unfortunately it's not possible to implement remote image uploading in a client library.

The best I could recommend would be to first download the image from the remote URL, then upload it into WordPress; but this will not result in the media record being created with a link to the remote file, so it is likely not what you wanted. Apologies!

**Comment by kadamwhite** [comment]
(I should clarify, if I misinterpreted your question please let me know)

**Comment by philohelp** [comment]
The solution given here (download then upload) seems to work fine. 
https://github.com/WP-API/node-wpapi/issues/455
