### ISSUE TITLE
Token Authentication for login from react

### ISSUE THREAD

**Issue by Barath-prakash** [WP-API/node-wpapi#377]
Please give me some idea to login with authentication (token) by using node-wpapi

**Comment by kadamwhite** [comment]
The best I can do is point you at https://GitHub.com/wp-api/oauth2. It’s not easy but it does work and I know that plugin is being used in production. Unfortunately you will need to se a separate library for HTTP requests, as we do not currently support OAuth 2 from this project. Good luck!
