### ISSUE TITLE
How to get total post count?

### ISSUE THREAD

**Issue by omgcyrilic** [WP-API/node-wpapi#378]
What would be the most efficient way to get the post count for all categories using wpapi?

I heard that the value for posts count is returned in the header as `X-WP-Total` but I'm new to react and I'm not sure what the best route is ...

Thanks!

**Comment by kadamwhite** [comment]
The simplest way should be this:
```js
wp.categories().get().then( response => {
    console.log( `There are ${ response._paging.total } categories on this site` );
} );
```
That said, this is documented here: http://wp-api.org/node-wpapi/collection-pagination/ If the documentation is insufficient or you were not able to find it, please let me know what improvements you might suggest. I don't have a ton of time to devote to this project right now and I'm concerned that I'm spending more time on support questions than improving the library itself, so if I can improve the docs, I would like to do so :)
