### ISSUE TITLE
media create date

### ISSUE THREAD

**Issue by arkamedus** [WP-API/node-wpapi#379]
I am trying to upload media, but the process fails and I don't get the .then() function being called.
This code works without the `date: filedate field`, and the date string I'm passing in is the same as I'm using for other other post creation. 

`this._wp.media()
.file(filepath)
.create({
     title: normalizer.get_image_title_from_filename(filepath),
     alt_text: '',
     caption: '',
     description: '',
     date: filedate
}).then(function (response) {
     cb(filepath, response);
});`

**Comment by kadamwhite** [comment]
Hello, @arkamedus ! I was unable to reproduce this issue; I successfully created media items with a variety of custom dates, formatted as `2018-12-31T05:00:00`. If you are still experiencing this problem, please leave a comment below noting more specifics and I'll do my best to assist (with a little less lag time on the response this year—apologies!)
