### ISSUE TITLE
Body of custom route request is empty

### ISSUE THREAD

**Issue by theturtleroom** [WP-API/node-wpapi#382]
Here is my code for setting up the route and the request itself. However, on the receiving end, it reads the userID argument, but says the body of the post is empty.

`wp.rcpUp = wp.registerRoute( 'rcp/v1/members', 'update/(?P<id>\\d+)' );`

`rcpUpdateData = {
				status: "active",
				subscription: 5,
				recurring: 1,
				expiration: expDate,
			}`

`wp.rcpUp().id(user.userID).update(rcpUpdateData)`

EDIT: Is there a way I could view the request without sending it to see all the pieces of the original request, so I can determine why the body is empty?

**Comment by theturtleroom** [comment]
bump

**Comment by kadamwhite** [comment]
@theturtleroom Thanks for the bump. Regarding your example, a few questions to double-check my understanding of what you are asking --

- Having `update` in the REST route is a little unusual, so just to check first off: you expect a PUT to `rcp/v1/members/update/<id>` will succeed? Does it work correctly with `curl` if you pass a json payload?
- I presume this record already exists, via creation on the WP side or from a prior `.create()`? If the latter, does `.create` work fine?

**Comment by theturtleroom** [comment]
This record does exists. The routes were designed by the makers of the plugin, and yes, update is in the route. It does succeed; I receive the positive response from the WP server. However, when I view the body from the WP end after it received the request, it says the body is empty.

I cannot get a `.create()` to work, either. I get the same positive response, but the body appears to be empty.

I am very new with doing HTTP requests...how would I craft a request through `curl` with a json payload?

**Comment by theturtleroom** [comment]
So, thanks....that was it The API was using `get_body_params()` instead of `get_json_params()`. Now I can get the full body to do what it is supposed to!.

**Comment by kadamwhite** [comment]
OK! @theturtleroom Does that mean you're sorted, now? Apologies not to provide a more specific curl example, but hope that it did end up helping you get to the answer!

**Comment by theturtleroom** [comment]
Yes! It is working now!

**Comment by kadamwhite** [comment]
Glad to hear it, thanks for following up!
