### ISSUE TITLE
updating custom post types

### ISSUE THREAD

**Issue by spinorial** [WP-API/node-wpapi#383]
Hi, I have created a custom post type with custom fields which I can create using the documented create method 

wp.custompost().create(data).then() 

However, I am running into problems when trying to update these custom posts, with regular posts you can use wp.posts().id(#number).update() however I cannot find a way to do this with wp.customposts().id(#number).

Any suggestions would be greatly appreciated.

Many thanks

**Comment by kadamwhite** [comment]
To properly answer your question @spinorial I'll need to know a little more about your custom post type. Are you using one of the default `wp/v2/your_cpt_name` routes? Or are you registering your own route? If so, can you share the example of how you're calling `registerRoute`?
