### ISSUE TITLE
Get blog name without being authenticated

### ISSUE THREAD

**Issue by gilesbutler** [WP-API/node-wpapi#384]
Hi,

Trying to figure out how to get the blogs name and description without having to authenticate via the `.settings` method. I can get them by doing a separate http request to `/wp-json` but I was hoping I didn't have to do another request. 

Appreciate any help you can provide.

Thanks

**Comment by kadamwhite** [comment]
Getting them via the `wp-json` endpoint is the correct approach. The easiest way to do this is to use the `.root()` method on a WPAPI instance.

```js
import WPAPI from 'wpapi';
const wp = new WPAPI( {
    endpoint: 'https://mysite.com/wp-json',
} );

wp.root().then( response => {
    console.log( `site name: ${ response.name }` );
    console.log( `site description: ${ response.description }` );
} );
```

**Comment by gilesbutler** [comment]
Amazing! Thanks @kadamwhite 👍
