### ISSUE TITLE
How to retrieve the number of likes?

### ISSUE THREAD

**Issue by whiteseagull** [WP-API/node-wpapi#386]
Hi,
given a post, how can I retrieve data about the likes it has? 
I didn't find anything in the docs.

**Comment by kadamwhite** [comment]
"likes" sounds like some sort of meta value on your post. The plugin you're using for likes would have to properly `register_post_meta()` or use `register_rest_field` to include this value in the post response. If it did that, you should see the data in the response object with no further work needed on the JS side.

Unfortunately, nothing you can do with this library on its own will help display likes if they do not already show up in the post response; I recommend contacting your plugin author to ask them to add REST API support for likes. Sorry we can't be of more assistance!
