### ISSUE TITLE
How to Hide products from WP REST API while Live on Website

### ISSUE THREAD

**Issue by UmeshRavani98** [WP-API/node-wpapi#387]
I am Using  Woocommerce 'Product Visibility' option to Hide woocommerce Products from Website, but while they're still visible in WP REST API Results which i am using to show Products on my Woocommerce ionic App.

Please help me with this

**Comment by kadamwhite** [comment]
You’ll need to bring this up with the product visibility plugin, I’m afraid. It’s possible they expose some meta value you can use to filter but it’s out of the scope of this library.

**Comment by UmeshRavani98** [comment]
Thank You @kadamwhite for your Response but, as i searched for Product Visibility Plugin I didn't found any that tricks WP REST API to hide.

Sir Any suggestions for Plugin..?

**Comment by kadamwhite** [comment]
I cannot provide support for that plugin. I’m sorry but you have to contact the people who make the plugin.
