### ISSUE TITLE
Error uploading large images using wp.media()

### ISSUE THREAD

**Issue by emascarinas** [WP-API/node-wpapi#389]
Errors out if file size is greater than 100mb.

wp.media().file(fileSrc).create()

{ Error: Internal Server Error
    at Request.callback (/Users/..node_modules/superagent/lib/node/index.js:706:15)
    at parser (/Users/..node_modules/superagent/lib/node/index.js:916:18)
    at IncomingMessage.res.on 
  status: 500,

Is there a config to change the upload size limit?

**Comment by kadamwhite** [comment]
Hey @emascarinas — I'm going to optimistically assume this is resolved with those php.ini changes, and close this out. If my assumption is incorrect and you're still experiencing this issue, please leave a comment with the additional information requested above, and we can re-open and attempt to resolve. Thank you for opening the issue!
