### ISSUE TITLE
Payload Too Large

### ISSUE THREAD

**Issue by cawa-93** [WP-API/node-wpapi#391]
I tried upload big mp3 files (over 100MB). In my server config:
```
php_value upload_max_filesize 300M
php_value post_max_size 300M
```
Help me figure out what causes the bug and how to fix it?

**Comment by morenoh149** [comment]
what's the error?

**Comment by kadamwhite** [comment]
Noting that I have reproduced this with [wpapi.local](https://github.com/kadamwhite/wpapi.local) and the following test script, using an MP3 file of over 100MB:

```js
const { join } = require( 'path' );
const WPAPI = require( './superagent' );
const site = new WPAPI( {
	endpoint: 'http://wpapi.local/wp-json',
	username: 'admin',
	password: 'password',
} );

const mp3Path = join( process.cwd(), 'kkgffffffsagsAAARGg (November 8, 2011).mp3' );
site.media()
	.file( mp3Path, 'kkgffffffsagsAAARGg.mp3' )
	.create( { title: 'Nov 8, 2011 DJ Mix', } )
	.then(
		r => console.log( r ),
		e => console.error( ( e.response && e.response.text ) || e )
	);
```

**Comment by kadamwhite** [comment]
Update: I could reproduce in an nginx environment, where despite the PHP configuration, the nginx site configuration specified
```
client_max-body_size 100M
```
Changing this to a higher value allowed the file through correctly.

I am going to close this out as unsolvable within this library; depending on the server environment some combination of PHP and Apache or Nginx configuration will be necessary to permit large uploads.
