### ISSUE TITLE
How I can use this behind poxy?

### ISSUE THREAD

**Issue by vmasule** [WP-API/node-wpapi#396]
This library works fine without proxy but doesn't work behind proxy. Help will be much appreciated.

**Comment by morenoh149** [comment]
This is a client, if your proxy is causing issues that's odd. The client should be using http and port 80 same as a browser. Could you clarify your question?

**Comment by vmasule** [comment]
@morenoh149  Thanks for reply. I am using it as a client only please see the code below which works fine without proxy but with proxy it throws error.

```
  var WPAPI = require( 'wpapi' );

var apiPromise = WPAPI.discover( 'https://mywebsite.com/' ).then(function( site ) {
    return site.auth({
        username: 'username',
        password: 'password'
    });
});

fs.readFile('template.html', 'utf8', (err, data) => {
    if (err) throw err;
    // console.log(data);
    // content = data;
    wp.posts().create({
        // "title" and "content" are the only required properties
        title: 'My sample post',
        categories: [8],
        content: data,
        // Post will be created as a draft by default if a specific "status"
        // is not specified
        status: 'publish'
    }).then(function( response ) {
        // "response" will hold all properties of your newly-created post,
        // including the unique `id` the post was assigned on creation
        console.log( response.id);
    }).catch(function( err ) {
        // handle error
        console.error(err);
    });
});

And it returns following error 

  { Error: connect ETIMEDOUT 34.249.83.111:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1158:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '34.249.83.111',
  port: 443,
  response: undefined }
```

**Comment by ferlores** [comment]
Same problem here. I need to run the client in a machine that is behind a proxy. Looking at the code it seems that we don't have a way to pass a proxy option to `agent`. Inside [invokeAndPromisify ](https://github.com/WP-API/node-wpapi/blob/master/lib/http-transport.js#L211) sounds like a good place to do it. What do you guys think?

**Comment by kadamwhite** [comment]
Merging with #324: if we provide a hook to specify a function to modify the request before it is sent, that should allow proxy options to be passed.
