### ISSUE TITLE
How omit credentials?

### ISSUE THREAD

**Issue by cawa-93** [WP-API/node-wpapi#400]
I use JWT plugin and node-wpapi in front-end in chrome extension.

I get access token without problems. If you check it, then it's valid:
```js
window.site.namespace('jwt-auth/v1').token().validate().create().then(console.log)
```
```json
{"code":"jwt_auth_valid_token","data":{"status":200}}
```
However, if I try to get information about the user, then I get a 401 error
```js
window.site.users().me().then(console.log)
```
```json
{"code":"rest_not_logged_in","message":"You are not currently logged in.","data":{"status":401}}
```
Experimenting I found that this behavior is present only if I am authorized on this site - in the cookie there are entries WordsPress. 
This is confirmed by the following tests:

```js
// credentials: include
fetch("http://example.com/wp-json/wp/v2/users/me", {"credentials":"include","headers":{"authorization":"Bearer <ACCESS_TOKEN>"}});
```
```json
{"code":"rest_not_logged_in","message":"You are not currently logged in.","data":{"status":401}}
```
```js
// credentials: omit
fetch("http://example.com/wp-json/wp/v2/users/me", {"credentials":"omit","headers":{"authorization":"Bearer <ACCESS_TOKEN>"}});
```
```json
{"id":1,"name":"example","url":"","description":"","link":"","slug":"example"}
```

How can I omit cookies using your library?

**Comment by kadamwhite** [comment]
falling back to cookie won't be a foolproof solution, because you may want to authenticate through JWT with a different user than is logged in; this is something I've run into a few times with folks using Basic Auth

**Comment by cawa-93** [comment]
@breadadams It was created here https://github.com/Tmeister/wp-api-jwt-auth/issues/133
