### ISSUE TITLE
Get posts in two or more categories ("and" operator) 

### ISSUE THREAD

**Issue by Rahmon** [WP-API/node-wpapi#412]
Hi.

`wp.posts().categories(arrayCategoryID)` returns posts with category X **or** Y. How can I return posts with category X **and** Y ?

**Comment by kadamwhite** [comment]
Unfortunately this is an outstanding weakness of the underlying API. It used to be possible using the now largely defunct rest-filter plugin, but we don’t have a good way to specify category_and with query parameters. 

 If this is something that you would like to see in WordPress, I would encourage you to open a ticket on the officials WP trac issue tracker; it would be useful functionality, to be sure!
