### ISSUE TITLE
V1.2.0 does not work with React-Native

### ISSUE THREAD

**Issue by el-lsan** [WP-API/node-wpapi#414]
After updating `wpapi` from `1.1.2` to `1.2.0`, my RN app does not run anymore and the packager throw following error:

```bundling failed: Error: Unable to resolve module `li` from `PROJECT_PATH/node_modules/wpapi/lib/autodiscovery.js`: Module `li` does not exist in the Haste module map```

As packager suggested, I did remove the `node_modules` folder, clean the cache and reinstall node modules and didn't help.
But running `yarn add li` and restarting the packager did help and fixed the issue.
However I don't see such note on this repo.

So either it's a bug in `1.2.0` or the readme file should be updated.

FYI, pretty much the same issue was happening with `url` module with version `1.1.2`. So with every new version of `node-wpapi` some dependencies are missing out of box 😄!

**Comment by jerolan** [comment]
It seems that the dependency "li" is marked as a devDependency i think it should be marked as a normal dependency

**Comment by kadamwhite** [comment]
Thank you @el-lsan for raising the issue, and @jerolan for the quick patch! I have merged this to the v1 branch and released v1.2.1 addressing the change.

**Comment by el-lsan** [comment]
@jerolan, @kadamwhite Thank you for your quick response/fix.
Cheers 🍻
