### ISSUE TITLE
How many replies with embed()?

### ISSUE THREAD

**Issue by whiteseagull** [WP-API/node-wpapi#423]
Hi! 
I'm using the lib (v. 1.1.2) to fetch post data with embedded author and comments, this way:
`wpapi.posts().perPage(numberOfPosts).embed() `
It works but I see that the maximum number of replies in ._embedded.replies[0] is set to 10.
I may be missing something but I haven't found any parameter to set the number of embedded replies... does it exist? How to fetch all the replies while embedding??
Thank you!
Francesco

**Comment by kadamwhite** [comment]
I believe this is a known deficiency of the underlying API. I’ll find the trac ticket and post here later, but unfortunately it is out of scope to fix this on the client level; the unfortunate result is that to properly handle large embedded collections, the best approach right now is to request without embed, then issue a follow up request to the resource collection endpoint specifying `?include=` IDs for the linked resources.

**Comment by whiteseagull** [comment]
Thank you for your reply. 
I've built a tool to read blogs. The problem is that some people close the access to the users endpoint, so to read the data about the author of the posts I need to use embed. 
Currently I make a request with posts().embed() to fetch the data about the posts and the author of them, and a subsequent call to replies() for each post. Unfortunately, there is no way to specify what data to embed in the embed call, so I'm getting some replies twice.

**Comment by kadamwhite** [comment]
https://core.trac.wordpress.org/ticket/43439 Here's the trac ticket; we're unfortunately unable to fix the cap-of-10-embedded-items issue within this library, so I'm going to close out the issue.

However, what you're discussing is interesting and touches on some discussion from [this other ticket](https://core.trac.wordpress.org/ticket/39696), which tracks discussion about how you'd be able to say, "please embed Author information but not Replies." I think that ticket will be the best solution long-term, but hopefully we'll make progress on both over the coming months. If you have any examples or suggestions to add to those threads, I'd welcome your comments!

Thanks for opening the issue, and my regrets it's out of scope for this project.
