### ISSUE TITLE
Update custom taxonomy on post?

### ISSUE THREAD

**Issue by selfagency** [WP-API/node-wpapi#430]
I’m trying to simplify a content migration by running a Node script using `node-wpapi`. Manual additions through the WP dashboard work and the taxonomy is REST enabled. When I try to update a custom taxonomy in my posts using the following code, my submission goes through without error, but my data doesn’t get updated:

```
await wp.posts().id(id).update({
  terms: { publication: pubID }
})
```

What am I doing wrong?

**Comment by kadamwhite** [comment]
How does the publication value get registered? Are you using register_rest_field, or register_term_meta?

**Comment by selfagency** [comment]
```php
    $args = array(
      'labels'                     => $labels,
      'hierarchical'               => true,
      'public'                     => true,
      'show_ui'                    => true,
      'show_admin_column'          => true,
      'show_in_nav_menus'          => true,
      'show_tagcloud'              => false,
      'show_in_rest'               => true,
      'rest_base'                  => 'publication',
      'rest_controller_class'      => 'WP_REST_Terms_Controller',
    );
    register_taxonomy('publication', array('post'), $args);
```

**Comment by selfagency** [comment]
here's the whole node script if it helps: https://gist.github.com/selfagency/720121ff9a28914d1c155c053ad6057b

**Comment by selfagency** [comment]
@kadamwhite Hey just circling back on this — any chance you could help me figure out what's going on?

**Comment by kadamwhite** [comment]
@selfagency Apologies for the delay, and thank you for the additional information. I think I see the issue: your custom taxonomy is a top-level key in the response object, not something nested beneath terms. What you'd want would look more like this:
```js
await wp.posts().id( id ).update( {
  publication: [ pubID ],
} );
```
where you're passing an array containing the ID of the associated publication custom terms as the `publication` key. I've tested this with a custom post type registered in the same way and I'm able to add or remove terms (by passing `[]`) correctly.

I'll leave this open for a bit in case you run into other trouble, but hope this helps!

**Comment by kadamwhite** [comment]
@selfagency Provisionally closing this as solved; please leave a comment if that's not the case :) Thanks for opening the issue!

**Comment by selfagency** [comment]
Sorry for not responding sooner, that worked, thank you!

**Comment by kadamwhite** [comment]
No worries, I’m glad to hear it! If you think the documentation could be improved I’d welcome a PR to clarify, but if not, happy developing!
