### ISSUE TITLE
Order By custom field 

### ISSUE THREAD

**Issue by lucaswerner90** [WP-API/node-wpapi#434]
Hi! First of all thanks for this package! It just makes everything easier! I'm trying to order a custom post type by a custom field, so when I do:

```
const callback = wp.customType()
            .order('desc')
            .orderby('votes');
```

I get (sorry the message is in Spanish):

```
{ code: 'rest_invalid_param',
  message: 'Parámetro(s) no válido(s): orderby',
  data:
   { status: 400,
     params:
      { orderby:
         'orderby no es ninguna de las siguientes author, date, id, include, modified, parent, relevance, slug, include_slugs, title.' } } }
```

How can I include my `votes` custom field to do this? Everything else works fine but the `orderby`

Thanks!

**Comment by kadamwhite** [comment]
Unfortunately solving this is out-of-scope for this library, as the orderby values supported by the REST API out-of-the-box are intentionally limited. You may add PHP code to your plugin or theme to permit this particular query, see [this thread from the original WP-API project repository](https://github.com/WP-API/WP-API/issues/2308) for more information. I think you'd then want to be passing `orderby( 'meta_value' )` if you go that route, however.
