### ISSUE TITLE
Issue with cookie authentication in a Node.js script

### ISSUE THREAD

**Issue by tk-o** [WP-API/node-wpapi#437]
Howdy 👋I'm trying to add some data-driven features to my automated tests suite. One of the elements I want to implement is a way to create a WP post with given list of properties.

I started looking for some tooling and found this project. I wrote a Node.js script to test if creating a post will be possible. I wanted to use cookie-based authorization as I can't count on any extra plugins.

My thinking can be described as the following:
1. I need a user to be authorized in order to get the nonce
  - I sign the user in using the web app endpoint
2. I have an authorized user, so calling the WP settings endpoint now
  - settings will contain the API root URL, current user ID and the nonce for them
3. I have the rightful nonce, so I use it to authorize my `WPAPI` instance calls
  - now what's left is to call `create` method on `posts` namespace and the new post is going to be created.

Unfortunately, I'm missing something.

I call the script this way: `API_HOST=https://wp.dev ADMIN_USER_NAME=admin ADMIN_USER_PASSWORD=1234 node wp-test.js` and then get this output:
```
etched WP settings { root: 'https://wp.dev/wp-json/',
  nonce: '072a22093d',
  userId: 1 }
accessing wp using { endpoint: 'https://wp.dev/wp-json/', nonce: '072a22093d' }
error in creating post { code: 'rest_cookie_invalid_nonce',
  message: 'Cookie nonce is invalid',
  data: { status: 403 } }
```

So the nonce gets created correctly for the user ID 1, and then the same nonce is passed to the `WPAPI`. The REST API says ` rest_cookie_invalid_nonce`.

**What am I missing?**

Here's the ajax endpoint for `wp_json_settings` action:
```php
// register the action for non-production env only
if (in_array(getenv('APPLICATION_ENV'), ['development', 'staging'])) {
    // add_action('wp_ajax_nopriv_wp_json_settings', 'wpjsonsettings');
    add_action('wp_ajax_wp_json_settings', 'wpjsonsettings');
}
​
function wpjsonsettings()
{
    echo json_encode([
        'root' => esc_url_raw(rest_url()),
        'nonce' => wp_create_nonce('wp_rest'),
        'userId' => get_current_user_id(),
    ]);
    exit;
}
```

The `wp-test.js` script:
```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';

const WPAPI = require('wpapi');
const request = require('request');

const { API_HOST, ADMIN_USER_NAME, ADMIN_USER_PASSWORD } = process.env;

init();

function init() {
  if (!API_HOST) {
    throw new Error('API_HOST is a required env var');
  }
  // first, authorize the user
  request({
    url: `${API_HOST}/wordpress/wp-login.php`,
    method: 'POST',
    jar: true,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: `log=${encodeValue(ADMIN_USER_NAME)}&pwd=${encodeValue(ADMIN_USER_PASSWORD)}`
  }, onAuthorized);
}
// helper for auth data formatting
function encodeValue(str) {
  return encodeURIComponent(str).replace(/!/g, '%21');
}

// once authorized, fetch the WP Settings for the current user
function onAuthorized(err, res, body) {
  request({
    url: `${API_HOST}/wordpress/wp-admin/admin-ajax.php?action=wp_json_settings`,
    method: 'GET',
    jar: true,
  }, onWpSettingsFetched)
}

// use the nonce devliered in WP settings to create a post
function onWpSettingsFetched(err, res, body) {
  const settings = JSON.parse(body);

  console.log('fetched WP settings', settings);

  createPost({
    endpoint: settings.root,
    nonce: settings.nonce,
  })
}

function createPost({ endpoint, nonce }) {
  console.log('accessing wp using', { endpoint, nonce })

  new WPAPI({
    endpoint,
    nonce
  })
    .posts()
    .create({
      title: 'Cypress post',
      content: 'Your post content for cypress test',
      type: 'post',
      status: 'publish',
    })
      .then(console.log)
      .catch(err => console.log('error in creating post', err));
}
```

**Comment by kadamwhite** [comment]
Cookie authentication is not really meant to be used from an external host; that’s specifically what the cookie/nonce pairing is intended to guard against. To authenticate remotely I’d recommend using the basic auth plugin (via SSL, always) or the OAuth 1.0a or OAuth 2 authentication plugins, all within this organization; however only basic auth is currently supported natively within this library. The way you’re describing doing login I would consider error prone and inadvisable. 

Probably not the answer you were looking for, but I hope this helps point you down a successful path!

**Comment by tk-o** [comment]
That's ok, the basic auth plugin is a tiny one (and it's not being released too often 🙃) so I'll just from the other plugin (that I am able to extend). It works fine 👍
