### ISSUE TITLE
where is the users email address?

### ISSUE THREAD

**Issue by KenEucker** [WP-API/node-wpapi#459]
The response from wp.users() returns user information but does not include the email address of the user. Why?

How do I retrieve the email address in this request?

**Comment by KenEucker** [comment]
> The response from wp.users() returns user information but does not include the email address of the user. Why?

I've been reading that this is a security concern and email addresses have been omitted from the pubic REST API. This makes sense.

> How do I retrieve the email address in this request?

My solution was to add the email address to the REST data as long as the REST user (using basic authentication) is an administrator: 

```
function register_email_rest_field( WP_REST_Response $response, WP_User $user, WP_REST_Request $request ){
	$rest_user = wp_get_current_user();
	if( in_array( 'administrator', $rest_user->roles ) ) {
		$response->data['email'] = $user->user_email;
	}

	return $response;

}
add_filter( 'rest_prepare_user', 'register_email_rest_field', 10, 3 );
```

**Comment by hayzem** [comment]
After all of the struggle with jwt token and rest api now I can't even get user email! Come on.
Maybe you could add this hook to https://github.com/WP-API/jwt-auth ?
