### ISSUE TITLE
Can wpapi client work with OAuth out of the box?

### ISSUE THREAD

**Issue by velara3** [WP-API/node-wpapi#473]
I'm not getting the Basic Authentication to work with wpapi client library. 

The [wpapi instructions](http://wp-api.org/node-wpapi/authentication/) recommend using the Basic Authentication plugin but the [Basic Authentication](https://github.com/WP-API/Basic-Auth) plugin recommends using OAuth 1.0 plugin. 

>To authenticate with your WordPress install, Download and install the Basic Authentication handler plugin on your target WordPress site. (Note that the basic auth handler is not curently available through the plugin repository: you must install it manually.) - http://wp-api.org/node-wpapi/authentication/

> Without SSL we strongly recommend using the OAuth 1.0a authentication handler in production environments. - https://github.com/WP-API/Basic-Auth

Since I'm not getting the Basic Auth to work and OAuth is recommended I'd like to setup OAuth. 

But if I install the OAuth plugin do I need to changing anything in the code? 

Here's what I have so far: 

	var wp = new WPAPI({
		endpoint: apiRoot,
		username: username,
		password: credential,
		auth: true
	});

	var test = wp.posts().create({
		title:'test',
		content:'test content'
	})
	.then(function(response) {
		console.log("complete");
		console.log(response);
	})
	.catch(function(err) {
		log("error:", err);
	})

	// error
	{ code: 'rest_cannot_create',
		message: 'Sorry, you are not allowed to create posts as this user.',
		data: { status: 401 } 
	}

FYI I'm using the download of wpapi.js (7/6/2017) here: 

http://wp-api.org/node-wpapi/installation/

I'm not on node. I'm on a client environment that runs ES6.

**Comment by kadamwhite** [comment]
It cannot work with OAuth yet. We hope to add it eventually, but the priority currently is the long-delayed rewrite of the internals to permit new transport methods.
