### ISSUE TITLE
Auth fails?

### ISSUE THREAD

**Issue by PanMan** [WP-API/node-wpapi#87]
Auth seems to fail, even when explicityly setting it in the call:

```
wp.users().auth("USER","PASS").me(); 
```

gives an empty object, while calling wp-json/users/me with basic auth with curl returns my user info.

**Comment by sebastienbarre** [comment]
Which server settings, if I may ask? I'm having issues to authenticate...

**Comment by kadamwhite** [comment]
@sebastienbarre what sort of trouble are you running into? Can you let us know the version of the WP-API plugin and basic Auth plugin you are using, and what server you are using? (E.g. Apache vs Nginx?)

**Comment by sebastienbarre** [comment]
Thanks for the quick reply @kadamwhite.
The issue comes from WP-API/Basic-Auth, which needs to be patched to support PHP in CGI/FastCGI mode. A PR was [submitted back in March](https://github.com/WP-API/Basic-Auth/pull/32), this would be greatly helpful.
